// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// BodyDeoldifyImageDeoldifyImagePost Body_deoldify_image_deoldify_image_post
//
// swagger:model Body_deoldify_image_deoldify_image_post
type BodyDeoldifyImageDeoldifyImagePost struct {

	// artistic
	Artistic *bool `json:"artistic,omitempty"`

	// image input
	InputImage string `json:"input_image,omitempty"`

	// render factor
	RenderFactor *int64 `json:"render_factor,omitempty"`
}

// Validate validates this body deoldify image deoldify image post
func (m *BodyDeoldifyImageDeoldifyImagePost) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this body deoldify image deoldify image post based on context it is used
func (m *BodyDeoldifyImageDeoldifyImagePost) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *BodyDeoldifyImageDeoldifyImagePost) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *BodyDeoldifyImageDeoldifyImagePost) UnmarshalBinary(b []byte) error {
	var res BodyDeoldifyImageDeoldifyImagePost
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
