// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// BodyDetectControlnetDetectPost Body_detect_controlnet_detect_post
//
// swagger:model Body_detect_controlnet_detect_post
type BodyDetectControlnetDetectPost struct {

	// Controlnet Input Images
	ControlnetInputImages []string `json:"controlnet_input_images"`

	// Controlnet Module
	ControlnetModule *string `json:"controlnet_module,omitempty"`

	// Controlnet Processor Resolution
	ControlnetProcessorRes *int64 `json:"controlnet_processor_res,omitempty"`

	// Controlnet Threshold a
	ControlnetThresholda *float64 `json:"controlnet_threshold_a,omitempty"`

	// Controlnet Threshold b
	ControlnetThresholdb *float64 `json:"controlnet_threshold_b,omitempty"`
}

// Validate validates this body detect controlnet detect post
func (m *BodyDetectControlnetDetectPost) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this body detect controlnet detect post based on context it is used
func (m *BodyDetectControlnetDetectPost) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *BodyDetectControlnetDetectPost) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *BodyDetectControlnetDetectPost) UnmarshalBinary(b []byte) error {
	var res BodyDetectControlnetDetectPost
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
