// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// Concept Concept
//
// swagger:model Concept
type Concept struct {

	// Class Data Dir
	ClassDataDir string `json:"class_data_dir,omitempty"`

	// Class Guidance Scale
	ClassGuidanceScale *float64 `json:"class_guidance_scale,omitempty"`

	// Class Infer Steps
	ClassInferSteps *int64 `json:"class_infer_steps,omitempty"`

	// Class Negative Prompt
	ClassNegativePrompt string `json:"class_negative_prompt,omitempty"`

	// Class Prompt
	ClassPrompt string `json:"class_prompt,omitempty"`

	// Class Token
	ClassToken string `json:"class_token,omitempty"`

	// Instance Data Dir
	InstanceDataDir string `json:"instance_data_dir,omitempty"`

	// Instance Prompt
	InstancePrompt string `json:"instance_prompt,omitempty"`

	// Instance Token
	InstanceToken string `json:"instance_token,omitempty"`

	// Is Valid
	IsValid *bool `json:"is_valid,omitempty"`

	// N Save Sample
	NSaveSample *int64 `json:"n_save_sample,omitempty"`

	// Num Class Images Per
	NumClassImagesPer int64 `json:"num_class_images_per,omitempty"`

	// Sample Seed
	SampleSeed *int64 `json:"sample_seed,omitempty"`

	// Save Guidance Scale
	SaveGuidanceScale *float64 `json:"save_guidance_scale,omitempty"`

	// Save Infer Steps
	SaveInferSteps *int64 `json:"save_infer_steps,omitempty"`

	// Save Sample Negative Prompt
	SaveSampleNegativePrompt string `json:"save_sample_negative_prompt,omitempty"`

	// Save Sample Prompt
	SaveSamplePrompt string `json:"save_sample_prompt,omitempty"`

	// Save Sample Template
	SaveSampleTemplate string `json:"save_sample_template,omitempty"`
}

// Validate validates this concept
func (m *Concept) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this concept based on context it is used
func (m *Concept) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *Concept) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *Concept) UnmarshalBinary(b []byte) error {
	var res Concept
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
