// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// DilateMaskRequest DilateMaskRequest
//
// swagger:model DilateMaskRequest
type DilateMaskRequest struct {

	// Dilate Amount
	DilateAmount *int64 `json:"dilate_amount,omitempty"`

	// Input Image
	// Required: true
	InputImage *string `json:"input_image"`

	// Mask
	// Required: true
	Mask *string `json:"mask"`
}

// Validate validates this dilate mask request
func (m *DilateMaskRequest) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateInputImage(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateMask(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *DilateMaskRequest) validateInputImage(formats strfmt.Registry) error {

	if err := validate.Required("input_image", "body", m.InputImage); err != nil {
		return err
	}

	return nil
}

func (m *DilateMaskRequest) validateMask(formats strfmt.Registry) error {

	if err := validate.Required("mask", "body", m.Mask); err != nil {
		return err
	}

	return nil
}

// ContextValidate validates this dilate mask request based on context it is used
func (m *DilateMaskRequest) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *DilateMaskRequest) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *DilateMaskRequest) UnmarshalBinary(b []byte) error {
	var res DilateMaskRequest
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
