// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// ExtrasSingleImageResponse ExtrasSingleImageResponse
//
// swagger:model ExtrasSingleImageResponse
type ExtrasSingleImageResponse struct {

	// HTML info
	//
	// A series of HTML tags containing the process info.
	// Required: true
	HTMLInfo *string `json:"html_info"`

	// Image
	//
	// The generated image in base64 format.
	Image string `json:"image,omitempty"`
}

// Validate validates this extras single image response
func (m *ExtrasSingleImageResponse) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateHTMLInfo(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *ExtrasSingleImageResponse) validateHTMLInfo(formats strfmt.Registry) error {

	if err := validate.Required("html_info", "body", m.HTMLInfo); err != nil {
		return err
	}

	return nil
}

// ContextValidate validates this extras single image response based on context it is used
func (m *ExtrasSingleImageResponse) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *ExtrasSingleImageResponse) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *ExtrasSingleImageResponse) UnmarshalBinary(b []byte) error {
	var res ExtrasSingleImageResponse
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
