// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// HTTPException HTTP exception
//
// swagger:model HTTPException
type HTTPException struct {

	// body
	Body string `json:"body,omitempty"`

	// detail
	Detail string `json:"detail,omitempty"`

	// error
	Error string `json:"error,omitempty"`

	// errors
	Errors string `json:"errors,omitempty"`
}

// Validate validates this HTTP exception
func (m *HTTPException) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this HTTP exception based on context it is used
func (m *HTTPException) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *HTTPException) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *HTTPException) UnmarshalBinary(b []byte) error {
	var res HTTPException
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
