// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// InstanceData InstanceData
//
// swagger:model InstanceData
type InstanceData struct {

	// File data
	//
	// Base64 representation of the file or URL
	// Required: true
	Data *string `json:"data"`

	// File name
	//
	// File name to save image as
	// Required: true
	Name *string `json:"name"`

	// Prompt
	//
	// Training prompt for image
	// Required: true
	Txt *string `json:"txt"`
}

// Validate validates this instance data
func (m *InstanceData) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateData(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateName(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateTxt(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *InstanceData) validateData(formats strfmt.Registry) error {

	if err := validate.Required("data", "body", m.Data); err != nil {
		return err
	}

	return nil
}

func (m *InstanceData) validateName(formats strfmt.Registry) error {

	if err := validate.Required("name", "body", m.Name); err != nil {
		return err
	}

	return nil
}

func (m *InstanceData) validateTxt(formats strfmt.Registry) error {

	if err := validate.Required("txt", "body", m.Txt); err != nil {
		return err
	}

	return nil
}

// ContextValidate validates this instance data based on context it is used
func (m *InstanceData) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *InstanceData) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *InstanceData) UnmarshalBinary(b []byte) error {
	var res InstanceData
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
