// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"strconv"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// SamAreaResponse SamAreaResponse
//
// swagger:model SamAreaResponse
type SamAreaResponse struct {

	// Masks
	// Required: true
	Masks []*MaskItem `json:"masks"`
}

// Validate validates this sam area response
func (m *SamAreaResponse) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateMasks(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *SamAreaResponse) validateMasks(formats strfmt.Registry) error {

	if err := validate.Required("masks", "body", m.Masks); err != nil {
		return err
	}

	for i := 0; i < len(m.Masks); i++ {
		if swag.IsZero(m.Masks[i]) { // not required
			continue
		}

		if m.Masks[i] != nil {
			if err := m.Masks[i].Validate(formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("masks" + "." + strconv.Itoa(i))
				} else if ce, ok := err.(*errors.CompositeError); ok {
					return ce.ValidateName("masks" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

// ContextValidate validate this sam area response based on the context it is used
func (m *SamAreaResponse) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := m.contextValidateMasks(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *SamAreaResponse) contextValidateMasks(ctx context.Context, formats strfmt.Registry) error {

	for i := 0; i < len(m.Masks); i++ {

		if m.Masks[i] != nil {
			if err := m.Masks[i].ContextValidate(ctx, formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("masks" + "." + strconv.Itoa(i))
				} else if ce, ok := err.(*errors.CompositeError); ok {
					return ce.ValidateName("masks" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

// MarshalBinary interface implementation
func (m *SamAreaResponse) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *SamAreaResponse) UnmarshalBinary(b []byte) error {
	var res SamAreaResponse
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
