// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"strconv"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// ScriptInfo ScriptInfo
//
// swagger:model ScriptInfo
type ScriptInfo struct {

	// Arguments
	//
	// List of script's arguments
	// Required: true
	Args []*ScriptArg `json:"args"`

	// IsAlwayson
	//
	// Flag specifying whether this script is an alwayson script
	IsAlwayson bool `json:"is_alwayson,omitempty"`

	// IsImg2img
	//
	// Flag specifying whether this script is an img2img script
	IsImg2img bool `json:"is_img2img,omitempty"`

	// Name
	//
	// Script name
	Name string `json:"name,omitempty"`
}

// Validate validates this script info
func (m *ScriptInfo) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateArgs(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *ScriptInfo) validateArgs(formats strfmt.Registry) error {

	if err := validate.Required("args", "body", m.Args); err != nil {
		return err
	}

	for i := 0; i < len(m.Args); i++ {
		if swag.IsZero(m.Args[i]) { // not required
			continue
		}

		if m.Args[i] != nil {
			if err := m.Args[i].Validate(formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("args" + "." + strconv.Itoa(i))
				} else if ce, ok := err.(*errors.CompositeError); ok {
					return ce.ValidateName("args" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

// ContextValidate validate this script info based on the context it is used
func (m *ScriptInfo) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := m.contextValidateArgs(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *ScriptInfo) contextValidateArgs(ctx context.Context, formats strfmt.Registry) error {

	for i := 0; i < len(m.Args); i++ {

		if m.Args[i] != nil {
			if err := m.Args[i].ContextValidate(ctx, formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("args" + "." + strconv.Itoa(i))
				} else if ce, ok := err.(*errors.CompositeError); ok {
					return ce.ValidateName("args" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

// MarshalBinary interface implementation
func (m *ScriptInfo) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *ScriptInfo) UnmarshalBinary(b []byte) error {
	var res ScriptInfo
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
