// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"github.com/SpenserCai/sd-webui-go/stablediffusion/models"
)

// NewAddCustomTagInfiniteImageBrowsingDbAddCustomTagPostParams creates a new AddCustomTagInfiniteImageBrowsingDbAddCustomTagPostParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewAddCustomTagInfiniteImageBrowsingDbAddCustomTagPostParams() *AddCustomTagInfiniteImageBrowsingDbAddCustomTagPostParams {
	return &AddCustomTagInfiniteImageBrowsingDbAddCustomTagPostParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewAddCustomTagInfiniteImageBrowsingDbAddCustomTagPostParamsWithTimeout creates a new AddCustomTagInfiniteImageBrowsingDbAddCustomTagPostParams object
// with the ability to set a timeout on a request.
func NewAddCustomTagInfiniteImageBrowsingDbAddCustomTagPostParamsWithTimeout(timeout time.Duration) *AddCustomTagInfiniteImageBrowsingDbAddCustomTagPostParams {
	return &AddCustomTagInfiniteImageBrowsingDbAddCustomTagPostParams{
		timeout: timeout,
	}
}

// NewAddCustomTagInfiniteImageBrowsingDbAddCustomTagPostParamsWithContext creates a new AddCustomTagInfiniteImageBrowsingDbAddCustomTagPostParams object
// with the ability to set a context for a request.
func NewAddCustomTagInfiniteImageBrowsingDbAddCustomTagPostParamsWithContext(ctx context.Context) *AddCustomTagInfiniteImageBrowsingDbAddCustomTagPostParams {
	return &AddCustomTagInfiniteImageBrowsingDbAddCustomTagPostParams{
		Context: ctx,
	}
}

// NewAddCustomTagInfiniteImageBrowsingDbAddCustomTagPostParamsWithHTTPClient creates a new AddCustomTagInfiniteImageBrowsingDbAddCustomTagPostParams object
// with the ability to set a custom HTTPClient for a request.
func NewAddCustomTagInfiniteImageBrowsingDbAddCustomTagPostParamsWithHTTPClient(client *http.Client) *AddCustomTagInfiniteImageBrowsingDbAddCustomTagPostParams {
	return &AddCustomTagInfiniteImageBrowsingDbAddCustomTagPostParams{
		HTTPClient: client,
	}
}

/*
AddCustomTagInfiniteImageBrowsingDbAddCustomTagPostParams contains all the parameters to send to the API endpoint

	for the add custom tag infinite image browsing db add custom tag post operation.

	Typically these are written to a http.Request.
*/
type AddCustomTagInfiniteImageBrowsingDbAddCustomTagPostParams struct {

	// Body.
	Body *models.AddCustomTagReq

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the add custom tag infinite image browsing db add custom tag post params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *AddCustomTagInfiniteImageBrowsingDbAddCustomTagPostParams) WithDefaults() *AddCustomTagInfiniteImageBrowsingDbAddCustomTagPostParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the add custom tag infinite image browsing db add custom tag post params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *AddCustomTagInfiniteImageBrowsingDbAddCustomTagPostParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the add custom tag infinite image browsing db add custom tag post params
func (o *AddCustomTagInfiniteImageBrowsingDbAddCustomTagPostParams) WithTimeout(timeout time.Duration) *AddCustomTagInfiniteImageBrowsingDbAddCustomTagPostParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the add custom tag infinite image browsing db add custom tag post params
func (o *AddCustomTagInfiniteImageBrowsingDbAddCustomTagPostParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the add custom tag infinite image browsing db add custom tag post params
func (o *AddCustomTagInfiniteImageBrowsingDbAddCustomTagPostParams) WithContext(ctx context.Context) *AddCustomTagInfiniteImageBrowsingDbAddCustomTagPostParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the add custom tag infinite image browsing db add custom tag post params
func (o *AddCustomTagInfiniteImageBrowsingDbAddCustomTagPostParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the add custom tag infinite image browsing db add custom tag post params
func (o *AddCustomTagInfiniteImageBrowsingDbAddCustomTagPostParams) WithHTTPClient(client *http.Client) *AddCustomTagInfiniteImageBrowsingDbAddCustomTagPostParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the add custom tag infinite image browsing db add custom tag post params
func (o *AddCustomTagInfiniteImageBrowsingDbAddCustomTagPostParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the add custom tag infinite image browsing db add custom tag post params
func (o *AddCustomTagInfiniteImageBrowsingDbAddCustomTagPostParams) WithBody(body *models.AddCustomTagReq) *AddCustomTagInfiniteImageBrowsingDbAddCustomTagPostParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the add custom tag infinite image browsing db add custom tag post params
func (o *AddCustomTagInfiniteImageBrowsingDbAddCustomTagPostParams) SetBody(body *models.AddCustomTagReq) {
	o.Body = body
}

// WriteToRequest writes these params to a swagger request
func (o *AddCustomTagInfiniteImageBrowsingDbAddCustomTagPostParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error
	if o.Body != nil {
		if err := r.SetBodyParam(o.Body); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
