// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/SpenserCai/sd-webui-go/stablediffusion/models"
)

// APISetSendImgPathInfiniteImageBrowsingSendImgPathPostReader is a Reader for the APISetSendImgPathInfiniteImageBrowsingSendImgPathPost structure.
type APISetSendImgPathInfiniteImageBrowsingSendImgPathPostReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *APISetSendImgPathInfiniteImageBrowsingSendImgPathPostReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewAPISetSendImgPathInfiniteImageBrowsingSendImgPathPostOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 422:
		result := NewAPISetSendImgPathInfiniteImageBrowsingSendImgPathPostUnprocessableEntity()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewAPISetSendImgPathInfiniteImageBrowsingSendImgPathPostOK creates a APISetSendImgPathInfiniteImageBrowsingSendImgPathPostOK with default headers values
func NewAPISetSendImgPathInfiniteImageBrowsingSendImgPathPostOK() *APISetSendImgPathInfiniteImageBrowsingSendImgPathPostOK {
	return &APISetSendImgPathInfiniteImageBrowsingSendImgPathPostOK{}
}

/*
APISetSendImgPathInfiniteImageBrowsingSendImgPathPostOK describes a response with status code 200, with default header values.

Successful Response
*/
type APISetSendImgPathInfiniteImageBrowsingSendImgPathPostOK struct {
	Payload interface{}
}

// IsSuccess returns true when this api set send img path infinite image browsing send img path post o k response has a 2xx status code
func (o *APISetSendImgPathInfiniteImageBrowsingSendImgPathPostOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this api set send img path infinite image browsing send img path post o k response has a 3xx status code
func (o *APISetSendImgPathInfiniteImageBrowsingSendImgPathPostOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this api set send img path infinite image browsing send img path post o k response has a 4xx status code
func (o *APISetSendImgPathInfiniteImageBrowsingSendImgPathPostOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this api set send img path infinite image browsing send img path post o k response has a 5xx status code
func (o *APISetSendImgPathInfiniteImageBrowsingSendImgPathPostOK) IsServerError() bool {
	return false
}

// IsCode returns true when this api set send img path infinite image browsing send img path post o k response a status code equal to that given
func (o *APISetSendImgPathInfiniteImageBrowsingSendImgPathPostOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the api set send img path infinite image browsing send img path post o k response
func (o *APISetSendImgPathInfiniteImageBrowsingSendImgPathPostOK) Code() int {
	return 200
}

func (o *APISetSendImgPathInfiniteImageBrowsingSendImgPathPostOK) Error() string {
	return fmt.Sprintf("[POST /infinite_image_browsing/send_img_path][%d] apiSetSendImgPathInfiniteImageBrowsingSendImgPathPostOK  %+v", 200, o.Payload)
}

func (o *APISetSendImgPathInfiniteImageBrowsingSendImgPathPostOK) String() string {
	return fmt.Sprintf("[POST /infinite_image_browsing/send_img_path][%d] apiSetSendImgPathInfiniteImageBrowsingSendImgPathPostOK  %+v", 200, o.Payload)
}

func (o *APISetSendImgPathInfiniteImageBrowsingSendImgPathPostOK) GetPayload() interface{} {
	return o.Payload
}

func (o *APISetSendImgPathInfiniteImageBrowsingSendImgPathPostOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewAPISetSendImgPathInfiniteImageBrowsingSendImgPathPostUnprocessableEntity creates a APISetSendImgPathInfiniteImageBrowsingSendImgPathPostUnprocessableEntity with default headers values
func NewAPISetSendImgPathInfiniteImageBrowsingSendImgPathPostUnprocessableEntity() *APISetSendImgPathInfiniteImageBrowsingSendImgPathPostUnprocessableEntity {
	return &APISetSendImgPathInfiniteImageBrowsingSendImgPathPostUnprocessableEntity{}
}

/*
APISetSendImgPathInfiniteImageBrowsingSendImgPathPostUnprocessableEntity describes a response with status code 422, with default header values.

Validation Error
*/
type APISetSendImgPathInfiniteImageBrowsingSendImgPathPostUnprocessableEntity struct {
	Payload *models.HTTPValidationError
}

// IsSuccess returns true when this api set send img path infinite image browsing send img path post unprocessable entity response has a 2xx status code
func (o *APISetSendImgPathInfiniteImageBrowsingSendImgPathPostUnprocessableEntity) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this api set send img path infinite image browsing send img path post unprocessable entity response has a 3xx status code
func (o *APISetSendImgPathInfiniteImageBrowsingSendImgPathPostUnprocessableEntity) IsRedirect() bool {
	return false
}

// IsClientError returns true when this api set send img path infinite image browsing send img path post unprocessable entity response has a 4xx status code
func (o *APISetSendImgPathInfiniteImageBrowsingSendImgPathPostUnprocessableEntity) IsClientError() bool {
	return true
}

// IsServerError returns true when this api set send img path infinite image browsing send img path post unprocessable entity response has a 5xx status code
func (o *APISetSendImgPathInfiniteImageBrowsingSendImgPathPostUnprocessableEntity) IsServerError() bool {
	return false
}

// IsCode returns true when this api set send img path infinite image browsing send img path post unprocessable entity response a status code equal to that given
func (o *APISetSendImgPathInfiniteImageBrowsingSendImgPathPostUnprocessableEntity) IsCode(code int) bool {
	return code == 422
}

// Code gets the status code for the api set send img path infinite image browsing send img path post unprocessable entity response
func (o *APISetSendImgPathInfiniteImageBrowsingSendImgPathPostUnprocessableEntity) Code() int {
	return 422
}

func (o *APISetSendImgPathInfiniteImageBrowsingSendImgPathPostUnprocessableEntity) Error() string {
	return fmt.Sprintf("[POST /infinite_image_browsing/send_img_path][%d] apiSetSendImgPathInfiniteImageBrowsingSendImgPathPostUnprocessableEntity  %+v", 422, o.Payload)
}

func (o *APISetSendImgPathInfiniteImageBrowsingSendImgPathPostUnprocessableEntity) String() string {
	return fmt.Sprintf("[POST /infinite_image_browsing/send_img_path][%d] apiSetSendImgPathInfiniteImageBrowsingSendImgPathPostUnprocessableEntity  %+v", 422, o.Payload)
}

func (o *APISetSendImgPathInfiniteImageBrowsingSendImgPathPostUnprocessableEntity) GetPayload() *models.HTTPValidationError {
	return o.Payload
}

func (o *APISetSendImgPathInfiniteImageBrowsingSendImgPathPostUnprocessableEntity) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.HTTPValidationError)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
