// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/SpenserCai/sd-webui-go/stablediffusion/models"
)

// APICategoryMaskSamCategoryMaskPostReader is a Reader for the APICategoryMaskSamCategoryMaskPost structure.
type APICategoryMaskSamCategoryMaskPostReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *APICategoryMaskSamCategoryMaskPostReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewAPICategoryMaskSamCategoryMaskPostOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 422:
		result := NewAPICategoryMaskSamCategoryMaskPostUnprocessableEntity()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewAPICategoryMaskSamCategoryMaskPostInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewAPICategoryMaskSamCategoryMaskPostOK creates a APICategoryMaskSamCategoryMaskPostOK with default headers values
func NewAPICategoryMaskSamCategoryMaskPostOK() *APICategoryMaskSamCategoryMaskPostOK {
	return &APICategoryMaskSamCategoryMaskPostOK{}
}

/*
APICategoryMaskSamCategoryMaskPostOK describes a response with status code 200, with default header values.

Successful Response
*/
type APICategoryMaskSamCategoryMaskPostOK struct {
	Payload interface{}
}

// IsSuccess returns true when this api category mask sam category mask post o k response has a 2xx status code
func (o *APICategoryMaskSamCategoryMaskPostOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this api category mask sam category mask post o k response has a 3xx status code
func (o *APICategoryMaskSamCategoryMaskPostOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this api category mask sam category mask post o k response has a 4xx status code
func (o *APICategoryMaskSamCategoryMaskPostOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this api category mask sam category mask post o k response has a 5xx status code
func (o *APICategoryMaskSamCategoryMaskPostOK) IsServerError() bool {
	return false
}

// IsCode returns true when this api category mask sam category mask post o k response a status code equal to that given
func (o *APICategoryMaskSamCategoryMaskPostOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the api category mask sam category mask post o k response
func (o *APICategoryMaskSamCategoryMaskPostOK) Code() int {
	return 200
}

func (o *APICategoryMaskSamCategoryMaskPostOK) Error() string {
	return fmt.Sprintf("[POST /sam/category-mask][%d] apiCategoryMaskSamCategoryMaskPostOK  %+v", 200, o.Payload)
}

func (o *APICategoryMaskSamCategoryMaskPostOK) String() string {
	return fmt.Sprintf("[POST /sam/category-mask][%d] apiCategoryMaskSamCategoryMaskPostOK  %+v", 200, o.Payload)
}

func (o *APICategoryMaskSamCategoryMaskPostOK) GetPayload() interface{} {
	return o.Payload
}

func (o *APICategoryMaskSamCategoryMaskPostOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewAPICategoryMaskSamCategoryMaskPostUnprocessableEntity creates a APICategoryMaskSamCategoryMaskPostUnprocessableEntity with default headers values
func NewAPICategoryMaskSamCategoryMaskPostUnprocessableEntity() *APICategoryMaskSamCategoryMaskPostUnprocessableEntity {
	return &APICategoryMaskSamCategoryMaskPostUnprocessableEntity{}
}

/*
APICategoryMaskSamCategoryMaskPostUnprocessableEntity describes a response with status code 422, with default header values.

Validation Error
*/
type APICategoryMaskSamCategoryMaskPostUnprocessableEntity struct {
	Payload *models.HTTPValidationError
}

// IsSuccess returns true when this api category mask sam category mask post unprocessable entity response has a 2xx status code
func (o *APICategoryMaskSamCategoryMaskPostUnprocessableEntity) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this api category mask sam category mask post unprocessable entity response has a 3xx status code
func (o *APICategoryMaskSamCategoryMaskPostUnprocessableEntity) IsRedirect() bool {
	return false
}

// IsClientError returns true when this api category mask sam category mask post unprocessable entity response has a 4xx status code
func (o *APICategoryMaskSamCategoryMaskPostUnprocessableEntity) IsClientError() bool {
	return true
}

// IsServerError returns true when this api category mask sam category mask post unprocessable entity response has a 5xx status code
func (o *APICategoryMaskSamCategoryMaskPostUnprocessableEntity) IsServerError() bool {
	return false
}

// IsCode returns true when this api category mask sam category mask post unprocessable entity response a status code equal to that given
func (o *APICategoryMaskSamCategoryMaskPostUnprocessableEntity) IsCode(code int) bool {
	return code == 422
}

// Code gets the status code for the api category mask sam category mask post unprocessable entity response
func (o *APICategoryMaskSamCategoryMaskPostUnprocessableEntity) Code() int {
	return 422
}

func (o *APICategoryMaskSamCategoryMaskPostUnprocessableEntity) Error() string {
	return fmt.Sprintf("[POST /sam/category-mask][%d] apiCategoryMaskSamCategoryMaskPostUnprocessableEntity  %+v", 422, o.Payload)
}

func (o *APICategoryMaskSamCategoryMaskPostUnprocessableEntity) String() string {
	return fmt.Sprintf("[POST /sam/category-mask][%d] apiCategoryMaskSamCategoryMaskPostUnprocessableEntity  %+v", 422, o.Payload)
}

func (o *APICategoryMaskSamCategoryMaskPostUnprocessableEntity) GetPayload() *models.HTTPValidationError {
	return o.Payload
}

func (o *APICategoryMaskSamCategoryMaskPostUnprocessableEntity) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.HTTPValidationError)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewAPICategoryMaskSamCategoryMaskPostInternalServerError creates a APICategoryMaskSamCategoryMaskPostInternalServerError with default headers values
func NewAPICategoryMaskSamCategoryMaskPostInternalServerError() *APICategoryMaskSamCategoryMaskPostInternalServerError {
	return &APICategoryMaskSamCategoryMaskPostInternalServerError{}
}

/*
APICategoryMaskSamCategoryMaskPostInternalServerError describes a response with status code 500, with default header values.

HTTPException
*/
type APICategoryMaskSamCategoryMaskPostInternalServerError struct {
	Payload *models.HTTPException
}

// IsSuccess returns true when this api category mask sam category mask post internal server error response has a 2xx status code
func (o *APICategoryMaskSamCategoryMaskPostInternalServerError) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this api category mask sam category mask post internal server error response has a 3xx status code
func (o *APICategoryMaskSamCategoryMaskPostInternalServerError) IsRedirect() bool {
	return false
}

// IsClientError returns true when this api category mask sam category mask post internal server error response has a 4xx status code
func (o *APICategoryMaskSamCategoryMaskPostInternalServerError) IsClientError() bool {
	return false
}

// IsServerError returns true when this api category mask sam category mask post internal server error response has a 5xx status code
func (o *APICategoryMaskSamCategoryMaskPostInternalServerError) IsServerError() bool {
	return true
}

// IsCode returns true when this api category mask sam category mask post internal server error response a status code equal to that given
func (o *APICategoryMaskSamCategoryMaskPostInternalServerError) IsCode(code int) bool {
	return code == 500
}

// Code gets the status code for the api category mask sam category mask post internal server error response
func (o *APICategoryMaskSamCategoryMaskPostInternalServerError) Code() int {
	return 500
}

func (o *APICategoryMaskSamCategoryMaskPostInternalServerError) Error() string {
	return fmt.Sprintf("[POST /sam/category-mask][%d] apiCategoryMaskSamCategoryMaskPostInternalServerError  %+v", 500, o.Payload)
}

func (o *APICategoryMaskSamCategoryMaskPostInternalServerError) String() string {
	return fmt.Sprintf("[POST /sam/category-mask][%d] apiCategoryMaskSamCategoryMaskPostInternalServerError  %+v", 500, o.Payload)
}

func (o *APICategoryMaskSamCategoryMaskPostInternalServerError) GetPayload() *models.HTTPException {
	return o.Payload
}

func (o *APICategoryMaskSamCategoryMaskPostInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.HTTPException)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
