// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/SpenserCai/sd-webui-go/stablediffusion/models"
)

// CheckPathExistsInfiniteImageBrowsingCheckPathExistsPostReader is a Reader for the CheckPathExistsInfiniteImageBrowsingCheckPathExistsPost structure.
type CheckPathExistsInfiniteImageBrowsingCheckPathExistsPostReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *CheckPathExistsInfiniteImageBrowsingCheckPathExistsPostReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewCheckPathExistsInfiniteImageBrowsingCheckPathExistsPostOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 422:
		result := NewCheckPathExistsInfiniteImageBrowsingCheckPathExistsPostUnprocessableEntity()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewCheckPathExistsInfiniteImageBrowsingCheckPathExistsPostOK creates a CheckPathExistsInfiniteImageBrowsingCheckPathExistsPostOK with default headers values
func NewCheckPathExistsInfiniteImageBrowsingCheckPathExistsPostOK() *CheckPathExistsInfiniteImageBrowsingCheckPathExistsPostOK {
	return &CheckPathExistsInfiniteImageBrowsingCheckPathExistsPostOK{}
}

/*
CheckPathExistsInfiniteImageBrowsingCheckPathExistsPostOK describes a response with status code 200, with default header values.

Successful Response
*/
type CheckPathExistsInfiniteImageBrowsingCheckPathExistsPostOK struct {
	Payload interface{}
}

// IsSuccess returns true when this check path exists infinite image browsing check path exists post o k response has a 2xx status code
func (o *CheckPathExistsInfiniteImageBrowsingCheckPathExistsPostOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this check path exists infinite image browsing check path exists post o k response has a 3xx status code
func (o *CheckPathExistsInfiniteImageBrowsingCheckPathExistsPostOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this check path exists infinite image browsing check path exists post o k response has a 4xx status code
func (o *CheckPathExistsInfiniteImageBrowsingCheckPathExistsPostOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this check path exists infinite image browsing check path exists post o k response has a 5xx status code
func (o *CheckPathExistsInfiniteImageBrowsingCheckPathExistsPostOK) IsServerError() bool {
	return false
}

// IsCode returns true when this check path exists infinite image browsing check path exists post o k response a status code equal to that given
func (o *CheckPathExistsInfiniteImageBrowsingCheckPathExistsPostOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the check path exists infinite image browsing check path exists post o k response
func (o *CheckPathExistsInfiniteImageBrowsingCheckPathExistsPostOK) Code() int {
	return 200
}

func (o *CheckPathExistsInfiniteImageBrowsingCheckPathExistsPostOK) Error() string {
	return fmt.Sprintf("[POST /infinite_image_browsing/check_path_exists][%d] checkPathExistsInfiniteImageBrowsingCheckPathExistsPostOK  %+v", 200, o.Payload)
}

func (o *CheckPathExistsInfiniteImageBrowsingCheckPathExistsPostOK) String() string {
	return fmt.Sprintf("[POST /infinite_image_browsing/check_path_exists][%d] checkPathExistsInfiniteImageBrowsingCheckPathExistsPostOK  %+v", 200, o.Payload)
}

func (o *CheckPathExistsInfiniteImageBrowsingCheckPathExistsPostOK) GetPayload() interface{} {
	return o.Payload
}

func (o *CheckPathExistsInfiniteImageBrowsingCheckPathExistsPostOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewCheckPathExistsInfiniteImageBrowsingCheckPathExistsPostUnprocessableEntity creates a CheckPathExistsInfiniteImageBrowsingCheckPathExistsPostUnprocessableEntity with default headers values
func NewCheckPathExistsInfiniteImageBrowsingCheckPathExistsPostUnprocessableEntity() *CheckPathExistsInfiniteImageBrowsingCheckPathExistsPostUnprocessableEntity {
	return &CheckPathExistsInfiniteImageBrowsingCheckPathExistsPostUnprocessableEntity{}
}

/*
CheckPathExistsInfiniteImageBrowsingCheckPathExistsPostUnprocessableEntity describes a response with status code 422, with default header values.

Validation Error
*/
type CheckPathExistsInfiniteImageBrowsingCheckPathExistsPostUnprocessableEntity struct {
	Payload *models.HTTPValidationError
}

// IsSuccess returns true when this check path exists infinite image browsing check path exists post unprocessable entity response has a 2xx status code
func (o *CheckPathExistsInfiniteImageBrowsingCheckPathExistsPostUnprocessableEntity) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this check path exists infinite image browsing check path exists post unprocessable entity response has a 3xx status code
func (o *CheckPathExistsInfiniteImageBrowsingCheckPathExistsPostUnprocessableEntity) IsRedirect() bool {
	return false
}

// IsClientError returns true when this check path exists infinite image browsing check path exists post unprocessable entity response has a 4xx status code
func (o *CheckPathExistsInfiniteImageBrowsingCheckPathExistsPostUnprocessableEntity) IsClientError() bool {
	return true
}

// IsServerError returns true when this check path exists infinite image browsing check path exists post unprocessable entity response has a 5xx status code
func (o *CheckPathExistsInfiniteImageBrowsingCheckPathExistsPostUnprocessableEntity) IsServerError() bool {
	return false
}

// IsCode returns true when this check path exists infinite image browsing check path exists post unprocessable entity response a status code equal to that given
func (o *CheckPathExistsInfiniteImageBrowsingCheckPathExistsPostUnprocessableEntity) IsCode(code int) bool {
	return code == 422
}

// Code gets the status code for the check path exists infinite image browsing check path exists post unprocessable entity response
func (o *CheckPathExistsInfiniteImageBrowsingCheckPathExistsPostUnprocessableEntity) Code() int {
	return 422
}

func (o *CheckPathExistsInfiniteImageBrowsingCheckPathExistsPostUnprocessableEntity) Error() string {
	return fmt.Sprintf("[POST /infinite_image_browsing/check_path_exists][%d] checkPathExistsInfiniteImageBrowsingCheckPathExistsPostUnprocessableEntity  %+v", 422, o.Payload)
}

func (o *CheckPathExistsInfiniteImageBrowsingCheckPathExistsPostUnprocessableEntity) String() string {
	return fmt.Sprintf("[POST /infinite_image_browsing/check_path_exists][%d] checkPathExistsInfiniteImageBrowsingCheckPathExistsPostUnprocessableEntity  %+v", 422, o.Payload)
}

func (o *CheckPathExistsInfiniteImageBrowsingCheckPathExistsPostUnprocessableEntity) GetPayload() *models.HTTPValidationError {
	return o.Payload
}

func (o *CheckPathExistsInfiniteImageBrowsingCheckPathExistsPostUnprocessableEntity) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.HTTPValidationError)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
