// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"github.com/SpenserCai/sd-webui-go/stablediffusion/models"
)

// NewCopyFilesInfiniteImageBrowsingCopyFilesPostParams creates a new CopyFilesInfiniteImageBrowsingCopyFilesPostParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewCopyFilesInfiniteImageBrowsingCopyFilesPostParams() *CopyFilesInfiniteImageBrowsingCopyFilesPostParams {
	return &CopyFilesInfiniteImageBrowsingCopyFilesPostParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewCopyFilesInfiniteImageBrowsingCopyFilesPostParamsWithTimeout creates a new CopyFilesInfiniteImageBrowsingCopyFilesPostParams object
// with the ability to set a timeout on a request.
func NewCopyFilesInfiniteImageBrowsingCopyFilesPostParamsWithTimeout(timeout time.Duration) *CopyFilesInfiniteImageBrowsingCopyFilesPostParams {
	return &CopyFilesInfiniteImageBrowsingCopyFilesPostParams{
		timeout: timeout,
	}
}

// NewCopyFilesInfiniteImageBrowsingCopyFilesPostParamsWithContext creates a new CopyFilesInfiniteImageBrowsingCopyFilesPostParams object
// with the ability to set a context for a request.
func NewCopyFilesInfiniteImageBrowsingCopyFilesPostParamsWithContext(ctx context.Context) *CopyFilesInfiniteImageBrowsingCopyFilesPostParams {
	return &CopyFilesInfiniteImageBrowsingCopyFilesPostParams{
		Context: ctx,
	}
}

// NewCopyFilesInfiniteImageBrowsingCopyFilesPostParamsWithHTTPClient creates a new CopyFilesInfiniteImageBrowsingCopyFilesPostParams object
// with the ability to set a custom HTTPClient for a request.
func NewCopyFilesInfiniteImageBrowsingCopyFilesPostParamsWithHTTPClient(client *http.Client) *CopyFilesInfiniteImageBrowsingCopyFilesPostParams {
	return &CopyFilesInfiniteImageBrowsingCopyFilesPostParams{
		HTTPClient: client,
	}
}

/*
CopyFilesInfiniteImageBrowsingCopyFilesPostParams contains all the parameters to send to the API endpoint

	for the copy files infinite image browsing copy files post operation.

	Typically these are written to a http.Request.
*/
type CopyFilesInfiniteImageBrowsingCopyFilesPostParams struct {

	// Body.
	Body *models.MoveFilesReq

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the copy files infinite image browsing copy files post params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *CopyFilesInfiniteImageBrowsingCopyFilesPostParams) WithDefaults() *CopyFilesInfiniteImageBrowsingCopyFilesPostParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the copy files infinite image browsing copy files post params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *CopyFilesInfiniteImageBrowsingCopyFilesPostParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the copy files infinite image browsing copy files post params
func (o *CopyFilesInfiniteImageBrowsingCopyFilesPostParams) WithTimeout(timeout time.Duration) *CopyFilesInfiniteImageBrowsingCopyFilesPostParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the copy files infinite image browsing copy files post params
func (o *CopyFilesInfiniteImageBrowsingCopyFilesPostParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the copy files infinite image browsing copy files post params
func (o *CopyFilesInfiniteImageBrowsingCopyFilesPostParams) WithContext(ctx context.Context) *CopyFilesInfiniteImageBrowsingCopyFilesPostParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the copy files infinite image browsing copy files post params
func (o *CopyFilesInfiniteImageBrowsingCopyFilesPostParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the copy files infinite image browsing copy files post params
func (o *CopyFilesInfiniteImageBrowsingCopyFilesPostParams) WithHTTPClient(client *http.Client) *CopyFilesInfiniteImageBrowsingCopyFilesPostParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the copy files infinite image browsing copy files post params
func (o *CopyFilesInfiniteImageBrowsingCopyFilesPostParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the copy files infinite image browsing copy files post params
func (o *CopyFilesInfiniteImageBrowsingCopyFilesPostParams) WithBody(body *models.MoveFilesReq) *CopyFilesInfiniteImageBrowsingCopyFilesPostParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the copy files infinite image browsing copy files post params
func (o *CopyFilesInfiniteImageBrowsingCopyFilesPostParams) SetBody(body *models.MoveFilesReq) {
	o.Body = body
}

// WriteToRequest writes these params to a swagger request
func (o *CopyFilesInfiniteImageBrowsingCopyFilesPostParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error
	if o.Body != nil {
		if err := r.SetBodyParam(o.Body); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
