// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewCreateEmbeddingSdapiV1CreateEmbeddingPostParams creates a new CreateEmbeddingSdapiV1CreateEmbeddingPostParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewCreateEmbeddingSdapiV1CreateEmbeddingPostParams() *CreateEmbeddingSdapiV1CreateEmbeddingPostParams {
	return &CreateEmbeddingSdapiV1CreateEmbeddingPostParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewCreateEmbeddingSdapiV1CreateEmbeddingPostParamsWithTimeout creates a new CreateEmbeddingSdapiV1CreateEmbeddingPostParams object
// with the ability to set a timeout on a request.
func NewCreateEmbeddingSdapiV1CreateEmbeddingPostParamsWithTimeout(timeout time.Duration) *CreateEmbeddingSdapiV1CreateEmbeddingPostParams {
	return &CreateEmbeddingSdapiV1CreateEmbeddingPostParams{
		timeout: timeout,
	}
}

// NewCreateEmbeddingSdapiV1CreateEmbeddingPostParamsWithContext creates a new CreateEmbeddingSdapiV1CreateEmbeddingPostParams object
// with the ability to set a context for a request.
func NewCreateEmbeddingSdapiV1CreateEmbeddingPostParamsWithContext(ctx context.Context) *CreateEmbeddingSdapiV1CreateEmbeddingPostParams {
	return &CreateEmbeddingSdapiV1CreateEmbeddingPostParams{
		Context: ctx,
	}
}

// NewCreateEmbeddingSdapiV1CreateEmbeddingPostParamsWithHTTPClient creates a new CreateEmbeddingSdapiV1CreateEmbeddingPostParams object
// with the ability to set a custom HTTPClient for a request.
func NewCreateEmbeddingSdapiV1CreateEmbeddingPostParamsWithHTTPClient(client *http.Client) *CreateEmbeddingSdapiV1CreateEmbeddingPostParams {
	return &CreateEmbeddingSdapiV1CreateEmbeddingPostParams{
		HTTPClient: client,
	}
}

/*
CreateEmbeddingSdapiV1CreateEmbeddingPostParams contains all the parameters to send to the API endpoint

	for the create embedding sdapi v1 create embedding post operation.

	Typically these are written to a http.Request.
*/
type CreateEmbeddingSdapiV1CreateEmbeddingPostParams struct {

	// Body.
	Body interface{}

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the create embedding sdapi v1 create embedding post params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *CreateEmbeddingSdapiV1CreateEmbeddingPostParams) WithDefaults() *CreateEmbeddingSdapiV1CreateEmbeddingPostParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the create embedding sdapi v1 create embedding post params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *CreateEmbeddingSdapiV1CreateEmbeddingPostParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the create embedding sdapi v1 create embedding post params
func (o *CreateEmbeddingSdapiV1CreateEmbeddingPostParams) WithTimeout(timeout time.Duration) *CreateEmbeddingSdapiV1CreateEmbeddingPostParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the create embedding sdapi v1 create embedding post params
func (o *CreateEmbeddingSdapiV1CreateEmbeddingPostParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the create embedding sdapi v1 create embedding post params
func (o *CreateEmbeddingSdapiV1CreateEmbeddingPostParams) WithContext(ctx context.Context) *CreateEmbeddingSdapiV1CreateEmbeddingPostParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the create embedding sdapi v1 create embedding post params
func (o *CreateEmbeddingSdapiV1CreateEmbeddingPostParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the create embedding sdapi v1 create embedding post params
func (o *CreateEmbeddingSdapiV1CreateEmbeddingPostParams) WithHTTPClient(client *http.Client) *CreateEmbeddingSdapiV1CreateEmbeddingPostParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the create embedding sdapi v1 create embedding post params
func (o *CreateEmbeddingSdapiV1CreateEmbeddingPostParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the create embedding sdapi v1 create embedding post params
func (o *CreateEmbeddingSdapiV1CreateEmbeddingPostParams) WithBody(body interface{}) *CreateEmbeddingSdapiV1CreateEmbeddingPostParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the create embedding sdapi v1 create embedding post params
func (o *CreateEmbeddingSdapiV1CreateEmbeddingPostParams) SetBody(body interface{}) {
	o.Body = body
}

// WriteToRequest writes these params to a swagger request
func (o *CreateEmbeddingSdapiV1CreateEmbeddingPostParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error
	if o.Body != nil {
		if err := r.SetBodyParam(o.Body); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
