// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/SpenserCai/sd-webui-go/stablediffusion/models"
)

// CreateScannedPathInfiniteImageBrowsingDbScannedPathsPostReader is a Reader for the CreateScannedPathInfiniteImageBrowsingDbScannedPathsPost structure.
type CreateScannedPathInfiniteImageBrowsingDbScannedPathsPostReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *CreateScannedPathInfiniteImageBrowsingDbScannedPathsPostReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 201:
		result := NewCreateScannedPathInfiniteImageBrowsingDbScannedPathsPostCreated()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 422:
		result := NewCreateScannedPathInfiniteImageBrowsingDbScannedPathsPostUnprocessableEntity()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewCreateScannedPathInfiniteImageBrowsingDbScannedPathsPostInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewCreateScannedPathInfiniteImageBrowsingDbScannedPathsPostCreated creates a CreateScannedPathInfiniteImageBrowsingDbScannedPathsPostCreated with default headers values
func NewCreateScannedPathInfiniteImageBrowsingDbScannedPathsPostCreated() *CreateScannedPathInfiniteImageBrowsingDbScannedPathsPostCreated {
	return &CreateScannedPathInfiniteImageBrowsingDbScannedPathsPostCreated{}
}

/*
CreateScannedPathInfiniteImageBrowsingDbScannedPathsPostCreated describes a response with status code 201, with default header values.

Successful Response
*/
type CreateScannedPathInfiniteImageBrowsingDbScannedPathsPostCreated struct {
	Payload interface{}
}

// IsSuccess returns true when this create scanned path infinite image browsing db scanned paths post created response has a 2xx status code
func (o *CreateScannedPathInfiniteImageBrowsingDbScannedPathsPostCreated) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this create scanned path infinite image browsing db scanned paths post created response has a 3xx status code
func (o *CreateScannedPathInfiniteImageBrowsingDbScannedPathsPostCreated) IsRedirect() bool {
	return false
}

// IsClientError returns true when this create scanned path infinite image browsing db scanned paths post created response has a 4xx status code
func (o *CreateScannedPathInfiniteImageBrowsingDbScannedPathsPostCreated) IsClientError() bool {
	return false
}

// IsServerError returns true when this create scanned path infinite image browsing db scanned paths post created response has a 5xx status code
func (o *CreateScannedPathInfiniteImageBrowsingDbScannedPathsPostCreated) IsServerError() bool {
	return false
}

// IsCode returns true when this create scanned path infinite image browsing db scanned paths post created response a status code equal to that given
func (o *CreateScannedPathInfiniteImageBrowsingDbScannedPathsPostCreated) IsCode(code int) bool {
	return code == 201
}

// Code gets the status code for the create scanned path infinite image browsing db scanned paths post created response
func (o *CreateScannedPathInfiniteImageBrowsingDbScannedPathsPostCreated) Code() int {
	return 201
}

func (o *CreateScannedPathInfiniteImageBrowsingDbScannedPathsPostCreated) Error() string {
	return fmt.Sprintf("[POST /infinite_image_browsing/db/scanned_paths][%d] createScannedPathInfiniteImageBrowsingDbScannedPathsPostCreated  %+v", 201, o.Payload)
}

func (o *CreateScannedPathInfiniteImageBrowsingDbScannedPathsPostCreated) String() string {
	return fmt.Sprintf("[POST /infinite_image_browsing/db/scanned_paths][%d] createScannedPathInfiniteImageBrowsingDbScannedPathsPostCreated  %+v", 201, o.Payload)
}

func (o *CreateScannedPathInfiniteImageBrowsingDbScannedPathsPostCreated) GetPayload() interface{} {
	return o.Payload
}

func (o *CreateScannedPathInfiniteImageBrowsingDbScannedPathsPostCreated) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewCreateScannedPathInfiniteImageBrowsingDbScannedPathsPostUnprocessableEntity creates a CreateScannedPathInfiniteImageBrowsingDbScannedPathsPostUnprocessableEntity with default headers values
func NewCreateScannedPathInfiniteImageBrowsingDbScannedPathsPostUnprocessableEntity() *CreateScannedPathInfiniteImageBrowsingDbScannedPathsPostUnprocessableEntity {
	return &CreateScannedPathInfiniteImageBrowsingDbScannedPathsPostUnprocessableEntity{}
}

/*
CreateScannedPathInfiniteImageBrowsingDbScannedPathsPostUnprocessableEntity describes a response with status code 422, with default header values.

Validation Error
*/
type CreateScannedPathInfiniteImageBrowsingDbScannedPathsPostUnprocessableEntity struct {
	Payload *models.HTTPValidationError
}

// IsSuccess returns true when this create scanned path infinite image browsing db scanned paths post unprocessable entity response has a 2xx status code
func (o *CreateScannedPathInfiniteImageBrowsingDbScannedPathsPostUnprocessableEntity) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this create scanned path infinite image browsing db scanned paths post unprocessable entity response has a 3xx status code
func (o *CreateScannedPathInfiniteImageBrowsingDbScannedPathsPostUnprocessableEntity) IsRedirect() bool {
	return false
}

// IsClientError returns true when this create scanned path infinite image browsing db scanned paths post unprocessable entity response has a 4xx status code
func (o *CreateScannedPathInfiniteImageBrowsingDbScannedPathsPostUnprocessableEntity) IsClientError() bool {
	return true
}

// IsServerError returns true when this create scanned path infinite image browsing db scanned paths post unprocessable entity response has a 5xx status code
func (o *CreateScannedPathInfiniteImageBrowsingDbScannedPathsPostUnprocessableEntity) IsServerError() bool {
	return false
}

// IsCode returns true when this create scanned path infinite image browsing db scanned paths post unprocessable entity response a status code equal to that given
func (o *CreateScannedPathInfiniteImageBrowsingDbScannedPathsPostUnprocessableEntity) IsCode(code int) bool {
	return code == 422
}

// Code gets the status code for the create scanned path infinite image browsing db scanned paths post unprocessable entity response
func (o *CreateScannedPathInfiniteImageBrowsingDbScannedPathsPostUnprocessableEntity) Code() int {
	return 422
}

func (o *CreateScannedPathInfiniteImageBrowsingDbScannedPathsPostUnprocessableEntity) Error() string {
	return fmt.Sprintf("[POST /infinite_image_browsing/db/scanned_paths][%d] createScannedPathInfiniteImageBrowsingDbScannedPathsPostUnprocessableEntity  %+v", 422, o.Payload)
}

func (o *CreateScannedPathInfiniteImageBrowsingDbScannedPathsPostUnprocessableEntity) String() string {
	return fmt.Sprintf("[POST /infinite_image_browsing/db/scanned_paths][%d] createScannedPathInfiniteImageBrowsingDbScannedPathsPostUnprocessableEntity  %+v", 422, o.Payload)
}

func (o *CreateScannedPathInfiniteImageBrowsingDbScannedPathsPostUnprocessableEntity) GetPayload() *models.HTTPValidationError {
	return o.Payload
}

func (o *CreateScannedPathInfiniteImageBrowsingDbScannedPathsPostUnprocessableEntity) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.HTTPValidationError)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewCreateScannedPathInfiniteImageBrowsingDbScannedPathsPostInternalServerError creates a CreateScannedPathInfiniteImageBrowsingDbScannedPathsPostInternalServerError with default headers values
func NewCreateScannedPathInfiniteImageBrowsingDbScannedPathsPostInternalServerError() *CreateScannedPathInfiniteImageBrowsingDbScannedPathsPostInternalServerError {
	return &CreateScannedPathInfiniteImageBrowsingDbScannedPathsPostInternalServerError{}
}

/*
CreateScannedPathInfiniteImageBrowsingDbScannedPathsPostInternalServerError describes a response with status code 500, with default header values.

HTTPException
*/
type CreateScannedPathInfiniteImageBrowsingDbScannedPathsPostInternalServerError struct {
	Payload *models.HTTPException
}

// IsSuccess returns true when this create scanned path infinite image browsing db scanned paths post internal server error response has a 2xx status code
func (o *CreateScannedPathInfiniteImageBrowsingDbScannedPathsPostInternalServerError) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this create scanned path infinite image browsing db scanned paths post internal server error response has a 3xx status code
func (o *CreateScannedPathInfiniteImageBrowsingDbScannedPathsPostInternalServerError) IsRedirect() bool {
	return false
}

// IsClientError returns true when this create scanned path infinite image browsing db scanned paths post internal server error response has a 4xx status code
func (o *CreateScannedPathInfiniteImageBrowsingDbScannedPathsPostInternalServerError) IsClientError() bool {
	return false
}

// IsServerError returns true when this create scanned path infinite image browsing db scanned paths post internal server error response has a 5xx status code
func (o *CreateScannedPathInfiniteImageBrowsingDbScannedPathsPostInternalServerError) IsServerError() bool {
	return true
}

// IsCode returns true when this create scanned path infinite image browsing db scanned paths post internal server error response a status code equal to that given
func (o *CreateScannedPathInfiniteImageBrowsingDbScannedPathsPostInternalServerError) IsCode(code int) bool {
	return code == 500
}

// Code gets the status code for the create scanned path infinite image browsing db scanned paths post internal server error response
func (o *CreateScannedPathInfiniteImageBrowsingDbScannedPathsPostInternalServerError) Code() int {
	return 500
}

func (o *CreateScannedPathInfiniteImageBrowsingDbScannedPathsPostInternalServerError) Error() string {
	return fmt.Sprintf("[POST /infinite_image_browsing/db/scanned_paths][%d] createScannedPathInfiniteImageBrowsingDbScannedPathsPostInternalServerError  %+v", 500, o.Payload)
}

func (o *CreateScannedPathInfiniteImageBrowsingDbScannedPathsPostInternalServerError) String() string {
	return fmt.Sprintf("[POST /infinite_image_browsing/db/scanned_paths][%d] createScannedPathInfiniteImageBrowsingDbScannedPathsPostInternalServerError  %+v", 500, o.Payload)
}

func (o *CreateScannedPathInfiniteImageBrowsingDbScannedPathsPostInternalServerError) GetPayload() *models.HTTPException {
	return o.Payload
}

func (o *CreateScannedPathInfiniteImageBrowsingDbScannedPathsPostInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.HTTPException)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
