// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/SpenserCai/sd-webui-go/stablediffusion/models"
)

// CreateEmbeddingSdapiV1CreateEmbeddingPostReader is a Reader for the CreateEmbeddingSdapiV1CreateEmbeddingPost structure.
type CreateEmbeddingSdapiV1CreateEmbeddingPostReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *CreateEmbeddingSdapiV1CreateEmbeddingPostReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewCreateEmbeddingSdapiV1CreateEmbeddingPostOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 422:
		result := NewCreateEmbeddingSdapiV1CreateEmbeddingPostUnprocessableEntity()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewCreateEmbeddingSdapiV1CreateEmbeddingPostOK creates a CreateEmbeddingSdapiV1CreateEmbeddingPostOK with default headers values
func NewCreateEmbeddingSdapiV1CreateEmbeddingPostOK() *CreateEmbeddingSdapiV1CreateEmbeddingPostOK {
	return &CreateEmbeddingSdapiV1CreateEmbeddingPostOK{}
}

/*
CreateEmbeddingSdapiV1CreateEmbeddingPostOK describes a response with status code 200, with default header values.

Successful Response
*/
type CreateEmbeddingSdapiV1CreateEmbeddingPostOK struct {
	Payload *models.CreateResponse
}

// IsSuccess returns true when this create embedding sdapi v1 create embedding post o k response has a 2xx status code
func (o *CreateEmbeddingSdapiV1CreateEmbeddingPostOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this create embedding sdapi v1 create embedding post o k response has a 3xx status code
func (o *CreateEmbeddingSdapiV1CreateEmbeddingPostOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this create embedding sdapi v1 create embedding post o k response has a 4xx status code
func (o *CreateEmbeddingSdapiV1CreateEmbeddingPostOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this create embedding sdapi v1 create embedding post o k response has a 5xx status code
func (o *CreateEmbeddingSdapiV1CreateEmbeddingPostOK) IsServerError() bool {
	return false
}

// IsCode returns true when this create embedding sdapi v1 create embedding post o k response a status code equal to that given
func (o *CreateEmbeddingSdapiV1CreateEmbeddingPostOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the create embedding sdapi v1 create embedding post o k response
func (o *CreateEmbeddingSdapiV1CreateEmbeddingPostOK) Code() int {
	return 200
}

func (o *CreateEmbeddingSdapiV1CreateEmbeddingPostOK) Error() string {
	return fmt.Sprintf("[POST /sdapi/v1/create/embedding][%d] createEmbeddingSdapiV1CreateEmbeddingPostOK  %+v", 200, o.Payload)
}

func (o *CreateEmbeddingSdapiV1CreateEmbeddingPostOK) String() string {
	return fmt.Sprintf("[POST /sdapi/v1/create/embedding][%d] createEmbeddingSdapiV1CreateEmbeddingPostOK  %+v", 200, o.Payload)
}

func (o *CreateEmbeddingSdapiV1CreateEmbeddingPostOK) GetPayload() *models.CreateResponse {
	return o.Payload
}

func (o *CreateEmbeddingSdapiV1CreateEmbeddingPostOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.CreateResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewCreateEmbeddingSdapiV1CreateEmbeddingPostUnprocessableEntity creates a CreateEmbeddingSdapiV1CreateEmbeddingPostUnprocessableEntity with default headers values
func NewCreateEmbeddingSdapiV1CreateEmbeddingPostUnprocessableEntity() *CreateEmbeddingSdapiV1CreateEmbeddingPostUnprocessableEntity {
	return &CreateEmbeddingSdapiV1CreateEmbeddingPostUnprocessableEntity{}
}

/*
CreateEmbeddingSdapiV1CreateEmbeddingPostUnprocessableEntity describes a response with status code 422, with default header values.

Validation Error
*/
type CreateEmbeddingSdapiV1CreateEmbeddingPostUnprocessableEntity struct {
	Payload *models.HTTPValidationError
}

// IsSuccess returns true when this create embedding sdapi v1 create embedding post unprocessable entity response has a 2xx status code
func (o *CreateEmbeddingSdapiV1CreateEmbeddingPostUnprocessableEntity) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this create embedding sdapi v1 create embedding post unprocessable entity response has a 3xx status code
func (o *CreateEmbeddingSdapiV1CreateEmbeddingPostUnprocessableEntity) IsRedirect() bool {
	return false
}

// IsClientError returns true when this create embedding sdapi v1 create embedding post unprocessable entity response has a 4xx status code
func (o *CreateEmbeddingSdapiV1CreateEmbeddingPostUnprocessableEntity) IsClientError() bool {
	return true
}

// IsServerError returns true when this create embedding sdapi v1 create embedding post unprocessable entity response has a 5xx status code
func (o *CreateEmbeddingSdapiV1CreateEmbeddingPostUnprocessableEntity) IsServerError() bool {
	return false
}

// IsCode returns true when this create embedding sdapi v1 create embedding post unprocessable entity response a status code equal to that given
func (o *CreateEmbeddingSdapiV1CreateEmbeddingPostUnprocessableEntity) IsCode(code int) bool {
	return code == 422
}

// Code gets the status code for the create embedding sdapi v1 create embedding post unprocessable entity response
func (o *CreateEmbeddingSdapiV1CreateEmbeddingPostUnprocessableEntity) Code() int {
	return 422
}

func (o *CreateEmbeddingSdapiV1CreateEmbeddingPostUnprocessableEntity) Error() string {
	return fmt.Sprintf("[POST /sdapi/v1/create/embedding][%d] createEmbeddingSdapiV1CreateEmbeddingPostUnprocessableEntity  %+v", 422, o.Payload)
}

func (o *CreateEmbeddingSdapiV1CreateEmbeddingPostUnprocessableEntity) String() string {
	return fmt.Sprintf("[POST /sdapi/v1/create/embedding][%d] createEmbeddingSdapiV1CreateEmbeddingPostUnprocessableEntity  %+v", 422, o.Payload)
}

func (o *CreateEmbeddingSdapiV1CreateEmbeddingPostUnprocessableEntity) GetPayload() *models.HTTPValidationError {
	return o.Payload
}

func (o *CreateEmbeddingSdapiV1CreateEmbeddingPostUnprocessableEntity) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.HTTPValidationError)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
