// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/SpenserCai/sd-webui-go/stablediffusion/models"
)

// DeleteFilesInfiniteImageBrowsingDeleteFilesPostReader is a Reader for the DeleteFilesInfiniteImageBrowsingDeleteFilesPost structure.
type DeleteFilesInfiniteImageBrowsingDeleteFilesPostReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *DeleteFilesInfiniteImageBrowsingDeleteFilesPostReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewDeleteFilesInfiniteImageBrowsingDeleteFilesPostOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 422:
		result := NewDeleteFilesInfiniteImageBrowsingDeleteFilesPostUnprocessableEntity()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewDeleteFilesInfiniteImageBrowsingDeleteFilesPostInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewDeleteFilesInfiniteImageBrowsingDeleteFilesPostOK creates a DeleteFilesInfiniteImageBrowsingDeleteFilesPostOK with default headers values
func NewDeleteFilesInfiniteImageBrowsingDeleteFilesPostOK() *DeleteFilesInfiniteImageBrowsingDeleteFilesPostOK {
	return &DeleteFilesInfiniteImageBrowsingDeleteFilesPostOK{}
}

/*
DeleteFilesInfiniteImageBrowsingDeleteFilesPostOK describes a response with status code 200, with default header values.

Successful Response
*/
type DeleteFilesInfiniteImageBrowsingDeleteFilesPostOK struct {
	Payload interface{}
}

// IsSuccess returns true when this delete files infinite image browsing delete files post o k response has a 2xx status code
func (o *DeleteFilesInfiniteImageBrowsingDeleteFilesPostOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this delete files infinite image browsing delete files post o k response has a 3xx status code
func (o *DeleteFilesInfiniteImageBrowsingDeleteFilesPostOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this delete files infinite image browsing delete files post o k response has a 4xx status code
func (o *DeleteFilesInfiniteImageBrowsingDeleteFilesPostOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this delete files infinite image browsing delete files post o k response has a 5xx status code
func (o *DeleteFilesInfiniteImageBrowsingDeleteFilesPostOK) IsServerError() bool {
	return false
}

// IsCode returns true when this delete files infinite image browsing delete files post o k response a status code equal to that given
func (o *DeleteFilesInfiniteImageBrowsingDeleteFilesPostOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the delete files infinite image browsing delete files post o k response
func (o *DeleteFilesInfiniteImageBrowsingDeleteFilesPostOK) Code() int {
	return 200
}

func (o *DeleteFilesInfiniteImageBrowsingDeleteFilesPostOK) Error() string {
	return fmt.Sprintf("[POST /infinite_image_browsing/delete_files][%d] deleteFilesInfiniteImageBrowsingDeleteFilesPostOK  %+v", 200, o.Payload)
}

func (o *DeleteFilesInfiniteImageBrowsingDeleteFilesPostOK) String() string {
	return fmt.Sprintf("[POST /infinite_image_browsing/delete_files][%d] deleteFilesInfiniteImageBrowsingDeleteFilesPostOK  %+v", 200, o.Payload)
}

func (o *DeleteFilesInfiniteImageBrowsingDeleteFilesPostOK) GetPayload() interface{} {
	return o.Payload
}

func (o *DeleteFilesInfiniteImageBrowsingDeleteFilesPostOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewDeleteFilesInfiniteImageBrowsingDeleteFilesPostUnprocessableEntity creates a DeleteFilesInfiniteImageBrowsingDeleteFilesPostUnprocessableEntity with default headers values
func NewDeleteFilesInfiniteImageBrowsingDeleteFilesPostUnprocessableEntity() *DeleteFilesInfiniteImageBrowsingDeleteFilesPostUnprocessableEntity {
	return &DeleteFilesInfiniteImageBrowsingDeleteFilesPostUnprocessableEntity{}
}

/*
DeleteFilesInfiniteImageBrowsingDeleteFilesPostUnprocessableEntity describes a response with status code 422, with default header values.

Validation Error
*/
type DeleteFilesInfiniteImageBrowsingDeleteFilesPostUnprocessableEntity struct {
	Payload *models.HTTPValidationError
}

// IsSuccess returns true when this delete files infinite image browsing delete files post unprocessable entity response has a 2xx status code
func (o *DeleteFilesInfiniteImageBrowsingDeleteFilesPostUnprocessableEntity) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this delete files infinite image browsing delete files post unprocessable entity response has a 3xx status code
func (o *DeleteFilesInfiniteImageBrowsingDeleteFilesPostUnprocessableEntity) IsRedirect() bool {
	return false
}

// IsClientError returns true when this delete files infinite image browsing delete files post unprocessable entity response has a 4xx status code
func (o *DeleteFilesInfiniteImageBrowsingDeleteFilesPostUnprocessableEntity) IsClientError() bool {
	return true
}

// IsServerError returns true when this delete files infinite image browsing delete files post unprocessable entity response has a 5xx status code
func (o *DeleteFilesInfiniteImageBrowsingDeleteFilesPostUnprocessableEntity) IsServerError() bool {
	return false
}

// IsCode returns true when this delete files infinite image browsing delete files post unprocessable entity response a status code equal to that given
func (o *DeleteFilesInfiniteImageBrowsingDeleteFilesPostUnprocessableEntity) IsCode(code int) bool {
	return code == 422
}

// Code gets the status code for the delete files infinite image browsing delete files post unprocessable entity response
func (o *DeleteFilesInfiniteImageBrowsingDeleteFilesPostUnprocessableEntity) Code() int {
	return 422
}

func (o *DeleteFilesInfiniteImageBrowsingDeleteFilesPostUnprocessableEntity) Error() string {
	return fmt.Sprintf("[POST /infinite_image_browsing/delete_files][%d] deleteFilesInfiniteImageBrowsingDeleteFilesPostUnprocessableEntity  %+v", 422, o.Payload)
}

func (o *DeleteFilesInfiniteImageBrowsingDeleteFilesPostUnprocessableEntity) String() string {
	return fmt.Sprintf("[POST /infinite_image_browsing/delete_files][%d] deleteFilesInfiniteImageBrowsingDeleteFilesPostUnprocessableEntity  %+v", 422, o.Payload)
}

func (o *DeleteFilesInfiniteImageBrowsingDeleteFilesPostUnprocessableEntity) GetPayload() *models.HTTPValidationError {
	return o.Payload
}

func (o *DeleteFilesInfiniteImageBrowsingDeleteFilesPostUnprocessableEntity) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.HTTPValidationError)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewDeleteFilesInfiniteImageBrowsingDeleteFilesPostInternalServerError creates a DeleteFilesInfiniteImageBrowsingDeleteFilesPostInternalServerError with default headers values
func NewDeleteFilesInfiniteImageBrowsingDeleteFilesPostInternalServerError() *DeleteFilesInfiniteImageBrowsingDeleteFilesPostInternalServerError {
	return &DeleteFilesInfiniteImageBrowsingDeleteFilesPostInternalServerError{}
}

/*
DeleteFilesInfiniteImageBrowsingDeleteFilesPostInternalServerError describes a response with status code 500, with default header values.

HTTPException
*/
type DeleteFilesInfiniteImageBrowsingDeleteFilesPostInternalServerError struct {
	Payload *models.HTTPException
}

// IsSuccess returns true when this delete files infinite image browsing delete files post internal server error response has a 2xx status code
func (o *DeleteFilesInfiniteImageBrowsingDeleteFilesPostInternalServerError) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this delete files infinite image browsing delete files post internal server error response has a 3xx status code
func (o *DeleteFilesInfiniteImageBrowsingDeleteFilesPostInternalServerError) IsRedirect() bool {
	return false
}

// IsClientError returns true when this delete files infinite image browsing delete files post internal server error response has a 4xx status code
func (o *DeleteFilesInfiniteImageBrowsingDeleteFilesPostInternalServerError) IsClientError() bool {
	return false
}

// IsServerError returns true when this delete files infinite image browsing delete files post internal server error response has a 5xx status code
func (o *DeleteFilesInfiniteImageBrowsingDeleteFilesPostInternalServerError) IsServerError() bool {
	return true
}

// IsCode returns true when this delete files infinite image browsing delete files post internal server error response a status code equal to that given
func (o *DeleteFilesInfiniteImageBrowsingDeleteFilesPostInternalServerError) IsCode(code int) bool {
	return code == 500
}

// Code gets the status code for the delete files infinite image browsing delete files post internal server error response
func (o *DeleteFilesInfiniteImageBrowsingDeleteFilesPostInternalServerError) Code() int {
	return 500
}

func (o *DeleteFilesInfiniteImageBrowsingDeleteFilesPostInternalServerError) Error() string {
	return fmt.Sprintf("[POST /infinite_image_browsing/delete_files][%d] deleteFilesInfiniteImageBrowsingDeleteFilesPostInternalServerError  %+v", 500, o.Payload)
}

func (o *DeleteFilesInfiniteImageBrowsingDeleteFilesPostInternalServerError) String() string {
	return fmt.Sprintf("[POST /infinite_image_browsing/delete_files][%d] deleteFilesInfiniteImageBrowsingDeleteFilesPostInternalServerError  %+v", 500, o.Payload)
}

func (o *DeleteFilesInfiniteImageBrowsingDeleteFilesPostInternalServerError) GetPayload() *models.HTTPException {
	return o.Payload
}

func (o *DeleteFilesInfiniteImageBrowsingDeleteFilesPostInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.HTTPException)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
