// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/SpenserCai/sd-webui-go/stablediffusion/models"
)

// GetMemorySdapiV1MemoryGetReader is a Reader for the GetMemorySdapiV1MemoryGet structure.
type GetMemorySdapiV1MemoryGetReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetMemorySdapiV1MemoryGetReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetMemorySdapiV1MemoryGetOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewGetMemorySdapiV1MemoryGetOK creates a GetMemorySdapiV1MemoryGetOK with default headers values
func NewGetMemorySdapiV1MemoryGetOK() *GetMemorySdapiV1MemoryGetOK {
	return &GetMemorySdapiV1MemoryGetOK{}
}

/*
GetMemorySdapiV1MemoryGetOK describes a response with status code 200, with default header values.

Successful Response
*/
type GetMemorySdapiV1MemoryGetOK struct {
	Payload *models.MemoryResponse
}

// IsSuccess returns true when this get memory sdapi v1 memory get o k response has a 2xx status code
func (o *GetMemorySdapiV1MemoryGetOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this get memory sdapi v1 memory get o k response has a 3xx status code
func (o *GetMemorySdapiV1MemoryGetOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get memory sdapi v1 memory get o k response has a 4xx status code
func (o *GetMemorySdapiV1MemoryGetOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this get memory sdapi v1 memory get o k response has a 5xx status code
func (o *GetMemorySdapiV1MemoryGetOK) IsServerError() bool {
	return false
}

// IsCode returns true when this get memory sdapi v1 memory get o k response a status code equal to that given
func (o *GetMemorySdapiV1MemoryGetOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the get memory sdapi v1 memory get o k response
func (o *GetMemorySdapiV1MemoryGetOK) Code() int {
	return 200
}

func (o *GetMemorySdapiV1MemoryGetOK) Error() string {
	return fmt.Sprintf("[GET /sdapi/v1/memory][%d] getMemorySdapiV1MemoryGetOK  %+v", 200, o.Payload)
}

func (o *GetMemorySdapiV1MemoryGetOK) String() string {
	return fmt.Sprintf("[GET /sdapi/v1/memory][%d] getMemorySdapiV1MemoryGetOK  %+v", 200, o.Payload)
}

func (o *GetMemorySdapiV1MemoryGetOK) GetPayload() *models.MemoryResponse {
	return o.Payload
}

func (o *GetMemorySdapiV1MemoryGetOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.MemoryResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
