// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewGetMemorySdapiV1MemoryGetParams creates a new GetMemorySdapiV1MemoryGetParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewGetMemorySdapiV1MemoryGetParams() *GetMemorySdapiV1MemoryGetParams {
	return &GetMemorySdapiV1MemoryGetParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewGetMemorySdapiV1MemoryGetParamsWithTimeout creates a new GetMemorySdapiV1MemoryGetParams object
// with the ability to set a timeout on a request.
func NewGetMemorySdapiV1MemoryGetParamsWithTimeout(timeout time.Duration) *GetMemorySdapiV1MemoryGetParams {
	return &GetMemorySdapiV1MemoryGetParams{
		timeout: timeout,
	}
}

// NewGetMemorySdapiV1MemoryGetParamsWithContext creates a new GetMemorySdapiV1MemoryGetParams object
// with the ability to set a context for a request.
func NewGetMemorySdapiV1MemoryGetParamsWithContext(ctx context.Context) *GetMemorySdapiV1MemoryGetParams {
	return &GetMemorySdapiV1MemoryGetParams{
		Context: ctx,
	}
}

// NewGetMemorySdapiV1MemoryGetParamsWithHTTPClient creates a new GetMemorySdapiV1MemoryGetParams object
// with the ability to set a custom HTTPClient for a request.
func NewGetMemorySdapiV1MemoryGetParamsWithHTTPClient(client *http.Client) *GetMemorySdapiV1MemoryGetParams {
	return &GetMemorySdapiV1MemoryGetParams{
		HTTPClient: client,
	}
}

/*
GetMemorySdapiV1MemoryGetParams contains all the parameters to send to the API endpoint

	for the get memory sdapi v1 memory get operation.

	Typically these are written to a http.Request.
*/
type GetMemorySdapiV1MemoryGetParams struct {
	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the get memory sdapi v1 memory get params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetMemorySdapiV1MemoryGetParams) WithDefaults() *GetMemorySdapiV1MemoryGetParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the get memory sdapi v1 memory get params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetMemorySdapiV1MemoryGetParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the get memory sdapi v1 memory get params
func (o *GetMemorySdapiV1MemoryGetParams) WithTimeout(timeout time.Duration) *GetMemorySdapiV1MemoryGetParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get memory sdapi v1 memory get params
func (o *GetMemorySdapiV1MemoryGetParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get memory sdapi v1 memory get params
func (o *GetMemorySdapiV1MemoryGetParams) WithContext(ctx context.Context) *GetMemorySdapiV1MemoryGetParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get memory sdapi v1 memory get params
func (o *GetMemorySdapiV1MemoryGetParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get memory sdapi v1 memory get params
func (o *GetMemorySdapiV1MemoryGetParams) WithHTTPClient(client *http.Client) *GetMemorySdapiV1MemoryGetParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get memory sdapi v1 memory get params
func (o *GetMemorySdapiV1MemoryGetParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WriteToRequest writes these params to a swagger request
func (o *GetMemorySdapiV1MemoryGetParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
