// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewGetImgSelectedCustomTagInfiniteImageBrowsingDbImgSelectedCustomTagGetParams creates a new GetImgSelectedCustomTagInfiniteImageBrowsingDbImgSelectedCustomTagGetParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewGetImgSelectedCustomTagInfiniteImageBrowsingDbImgSelectedCustomTagGetParams() *GetImgSelectedCustomTagInfiniteImageBrowsingDbImgSelectedCustomTagGetParams {
	return &GetImgSelectedCustomTagInfiniteImageBrowsingDbImgSelectedCustomTagGetParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewGetImgSelectedCustomTagInfiniteImageBrowsingDbImgSelectedCustomTagGetParamsWithTimeout creates a new GetImgSelectedCustomTagInfiniteImageBrowsingDbImgSelectedCustomTagGetParams object
// with the ability to set a timeout on a request.
func NewGetImgSelectedCustomTagInfiniteImageBrowsingDbImgSelectedCustomTagGetParamsWithTimeout(timeout time.Duration) *GetImgSelectedCustomTagInfiniteImageBrowsingDbImgSelectedCustomTagGetParams {
	return &GetImgSelectedCustomTagInfiniteImageBrowsingDbImgSelectedCustomTagGetParams{
		timeout: timeout,
	}
}

// NewGetImgSelectedCustomTagInfiniteImageBrowsingDbImgSelectedCustomTagGetParamsWithContext creates a new GetImgSelectedCustomTagInfiniteImageBrowsingDbImgSelectedCustomTagGetParams object
// with the ability to set a context for a request.
func NewGetImgSelectedCustomTagInfiniteImageBrowsingDbImgSelectedCustomTagGetParamsWithContext(ctx context.Context) *GetImgSelectedCustomTagInfiniteImageBrowsingDbImgSelectedCustomTagGetParams {
	return &GetImgSelectedCustomTagInfiniteImageBrowsingDbImgSelectedCustomTagGetParams{
		Context: ctx,
	}
}

// NewGetImgSelectedCustomTagInfiniteImageBrowsingDbImgSelectedCustomTagGetParamsWithHTTPClient creates a new GetImgSelectedCustomTagInfiniteImageBrowsingDbImgSelectedCustomTagGetParams object
// with the ability to set a custom HTTPClient for a request.
func NewGetImgSelectedCustomTagInfiniteImageBrowsingDbImgSelectedCustomTagGetParamsWithHTTPClient(client *http.Client) *GetImgSelectedCustomTagInfiniteImageBrowsingDbImgSelectedCustomTagGetParams {
	return &GetImgSelectedCustomTagInfiniteImageBrowsingDbImgSelectedCustomTagGetParams{
		HTTPClient: client,
	}
}

/*
GetImgSelectedCustomTagInfiniteImageBrowsingDbImgSelectedCustomTagGetParams contains all the parameters to send to the API endpoint

	for the get img selected custom tag infinite image browsing db img selected custom tag get operation.

	Typically these are written to a http.Request.
*/
type GetImgSelectedCustomTagInfiniteImageBrowsingDbImgSelectedCustomTagGetParams struct {

	// Path.
	Path string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the get img selected custom tag infinite image browsing db img selected custom tag get params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetImgSelectedCustomTagInfiniteImageBrowsingDbImgSelectedCustomTagGetParams) WithDefaults() *GetImgSelectedCustomTagInfiniteImageBrowsingDbImgSelectedCustomTagGetParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the get img selected custom tag infinite image browsing db img selected custom tag get params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetImgSelectedCustomTagInfiniteImageBrowsingDbImgSelectedCustomTagGetParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the get img selected custom tag infinite image browsing db img selected custom tag get params
func (o *GetImgSelectedCustomTagInfiniteImageBrowsingDbImgSelectedCustomTagGetParams) WithTimeout(timeout time.Duration) *GetImgSelectedCustomTagInfiniteImageBrowsingDbImgSelectedCustomTagGetParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get img selected custom tag infinite image browsing db img selected custom tag get params
func (o *GetImgSelectedCustomTagInfiniteImageBrowsingDbImgSelectedCustomTagGetParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get img selected custom tag infinite image browsing db img selected custom tag get params
func (o *GetImgSelectedCustomTagInfiniteImageBrowsingDbImgSelectedCustomTagGetParams) WithContext(ctx context.Context) *GetImgSelectedCustomTagInfiniteImageBrowsingDbImgSelectedCustomTagGetParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get img selected custom tag infinite image browsing db img selected custom tag get params
func (o *GetImgSelectedCustomTagInfiniteImageBrowsingDbImgSelectedCustomTagGetParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get img selected custom tag infinite image browsing db img selected custom tag get params
func (o *GetImgSelectedCustomTagInfiniteImageBrowsingDbImgSelectedCustomTagGetParams) WithHTTPClient(client *http.Client) *GetImgSelectedCustomTagInfiniteImageBrowsingDbImgSelectedCustomTagGetParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get img selected custom tag infinite image browsing db img selected custom tag get params
func (o *GetImgSelectedCustomTagInfiniteImageBrowsingDbImgSelectedCustomTagGetParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithPath adds the path to the get img selected custom tag infinite image browsing db img selected custom tag get params
func (o *GetImgSelectedCustomTagInfiniteImageBrowsingDbImgSelectedCustomTagGetParams) WithPath(path string) *GetImgSelectedCustomTagInfiniteImageBrowsingDbImgSelectedCustomTagGetParams {
	o.SetPath(path)
	return o
}

// SetPath adds the path to the get img selected custom tag infinite image browsing db img selected custom tag get params
func (o *GetImgSelectedCustomTagInfiniteImageBrowsingDbImgSelectedCustomTagGetParams) SetPath(path string) {
	o.Path = path
}

// WriteToRequest writes these params to a swagger request
func (o *GetImgSelectedCustomTagInfiniteImageBrowsingDbImgSelectedCustomTagGetParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// query param path
	qrPath := o.Path
	qPath := qrPath
	if qPath != "" {

		if err := r.SetQueryParam("path", qPath); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
