// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/SpenserCai/sd-webui-go/stablediffusion/models"
)

// GetFaceRestorersSdapiV1FaceRestorersGetReader is a Reader for the GetFaceRestorersSdapiV1FaceRestorersGet structure.
type GetFaceRestorersSdapiV1FaceRestorersGetReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetFaceRestorersSdapiV1FaceRestorersGetReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetFaceRestorersSdapiV1FaceRestorersGetOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewGetFaceRestorersSdapiV1FaceRestorersGetOK creates a GetFaceRestorersSdapiV1FaceRestorersGetOK with default headers values
func NewGetFaceRestorersSdapiV1FaceRestorersGetOK() *GetFaceRestorersSdapiV1FaceRestorersGetOK {
	return &GetFaceRestorersSdapiV1FaceRestorersGetOK{}
}

/*
GetFaceRestorersSdapiV1FaceRestorersGetOK describes a response with status code 200, with default header values.

Successful Response
*/
type GetFaceRestorersSdapiV1FaceRestorersGetOK struct {
	Payload []*models.FaceRestorerItem
}

// IsSuccess returns true when this get face restorers sdapi v1 face restorers get o k response has a 2xx status code
func (o *GetFaceRestorersSdapiV1FaceRestorersGetOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this get face restorers sdapi v1 face restorers get o k response has a 3xx status code
func (o *GetFaceRestorersSdapiV1FaceRestorersGetOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get face restorers sdapi v1 face restorers get o k response has a 4xx status code
func (o *GetFaceRestorersSdapiV1FaceRestorersGetOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this get face restorers sdapi v1 face restorers get o k response has a 5xx status code
func (o *GetFaceRestorersSdapiV1FaceRestorersGetOK) IsServerError() bool {
	return false
}

// IsCode returns true when this get face restorers sdapi v1 face restorers get o k response a status code equal to that given
func (o *GetFaceRestorersSdapiV1FaceRestorersGetOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the get face restorers sdapi v1 face restorers get o k response
func (o *GetFaceRestorersSdapiV1FaceRestorersGetOK) Code() int {
	return 200
}

func (o *GetFaceRestorersSdapiV1FaceRestorersGetOK) Error() string {
	return fmt.Sprintf("[GET /sdapi/v1/face-restorers][%d] getFaceRestorersSdapiV1FaceRestorersGetOK  %+v", 200, o.Payload)
}

func (o *GetFaceRestorersSdapiV1FaceRestorersGetOK) String() string {
	return fmt.Sprintf("[GET /sdapi/v1/face-restorers][%d] getFaceRestorersSdapiV1FaceRestorersGetOK  %+v", 200, o.Payload)
}

func (o *GetFaceRestorersSdapiV1FaceRestorersGetOK) GetPayload() []*models.FaceRestorerItem {
	return o.Payload
}

func (o *GetFaceRestorersSdapiV1FaceRestorersGetOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
