// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewGetUpscalersSdapiV1UpscalersGetParams creates a new GetUpscalersSdapiV1UpscalersGetParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewGetUpscalersSdapiV1UpscalersGetParams() *GetUpscalersSdapiV1UpscalersGetParams {
	return &GetUpscalersSdapiV1UpscalersGetParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewGetUpscalersSdapiV1UpscalersGetParamsWithTimeout creates a new GetUpscalersSdapiV1UpscalersGetParams object
// with the ability to set a timeout on a request.
func NewGetUpscalersSdapiV1UpscalersGetParamsWithTimeout(timeout time.Duration) *GetUpscalersSdapiV1UpscalersGetParams {
	return &GetUpscalersSdapiV1UpscalersGetParams{
		timeout: timeout,
	}
}

// NewGetUpscalersSdapiV1UpscalersGetParamsWithContext creates a new GetUpscalersSdapiV1UpscalersGetParams object
// with the ability to set a context for a request.
func NewGetUpscalersSdapiV1UpscalersGetParamsWithContext(ctx context.Context) *GetUpscalersSdapiV1UpscalersGetParams {
	return &GetUpscalersSdapiV1UpscalersGetParams{
		Context: ctx,
	}
}

// NewGetUpscalersSdapiV1UpscalersGetParamsWithHTTPClient creates a new GetUpscalersSdapiV1UpscalersGetParams object
// with the ability to set a custom HTTPClient for a request.
func NewGetUpscalersSdapiV1UpscalersGetParamsWithHTTPClient(client *http.Client) *GetUpscalersSdapiV1UpscalersGetParams {
	return &GetUpscalersSdapiV1UpscalersGetParams{
		HTTPClient: client,
	}
}

/*
GetUpscalersSdapiV1UpscalersGetParams contains all the parameters to send to the API endpoint

	for the get upscalers sdapi v1 upscalers get operation.

	Typically these are written to a http.Request.
*/
type GetUpscalersSdapiV1UpscalersGetParams struct {
	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the get upscalers sdapi v1 upscalers get params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetUpscalersSdapiV1UpscalersGetParams) WithDefaults() *GetUpscalersSdapiV1UpscalersGetParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the get upscalers sdapi v1 upscalers get params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetUpscalersSdapiV1UpscalersGetParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the get upscalers sdapi v1 upscalers get params
func (o *GetUpscalersSdapiV1UpscalersGetParams) WithTimeout(timeout time.Duration) *GetUpscalersSdapiV1UpscalersGetParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get upscalers sdapi v1 upscalers get params
func (o *GetUpscalersSdapiV1UpscalersGetParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get upscalers sdapi v1 upscalers get params
func (o *GetUpscalersSdapiV1UpscalersGetParams) WithContext(ctx context.Context) *GetUpscalersSdapiV1UpscalersGetParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get upscalers sdapi v1 upscalers get params
func (o *GetUpscalersSdapiV1UpscalersGetParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get upscalers sdapi v1 upscalers get params
func (o *GetUpscalersSdapiV1UpscalersGetParams) WithHTTPClient(client *http.Client) *GetUpscalersSdapiV1UpscalersGetParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get upscalers sdapi v1 upscalers get params
func (o *GetUpscalersSdapiV1UpscalersGetParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WriteToRequest writes these params to a swagger request
func (o *GetUpscalersSdapiV1UpscalersGetParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
