// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// GetDbBasicInfoInfiniteImageBrowsingDbBasicInfoGetReader is a Reader for the GetDbBasicInfoInfiniteImageBrowsingDbBasicInfoGet structure.
type GetDbBasicInfoInfiniteImageBrowsingDbBasicInfoGetReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetDbBasicInfoInfiniteImageBrowsingDbBasicInfoGetReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetDbBasicInfoInfiniteImageBrowsingDbBasicInfoGetOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewGetDbBasicInfoInfiniteImageBrowsingDbBasicInfoGetOK creates a GetDbBasicInfoInfiniteImageBrowsingDbBasicInfoGetOK with default headers values
func NewGetDbBasicInfoInfiniteImageBrowsingDbBasicInfoGetOK() *GetDbBasicInfoInfiniteImageBrowsingDbBasicInfoGetOK {
	return &GetDbBasicInfoInfiniteImageBrowsingDbBasicInfoGetOK{}
}

/*
GetDbBasicInfoInfiniteImageBrowsingDbBasicInfoGetOK describes a response with status code 200, with default header values.

Successful Response
*/
type GetDbBasicInfoInfiniteImageBrowsingDbBasicInfoGetOK struct {
	Payload interface{}
}

// IsSuccess returns true when this get db basic info infinite image browsing db basic info get o k response has a 2xx status code
func (o *GetDbBasicInfoInfiniteImageBrowsingDbBasicInfoGetOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this get db basic info infinite image browsing db basic info get o k response has a 3xx status code
func (o *GetDbBasicInfoInfiniteImageBrowsingDbBasicInfoGetOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get db basic info infinite image browsing db basic info get o k response has a 4xx status code
func (o *GetDbBasicInfoInfiniteImageBrowsingDbBasicInfoGetOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this get db basic info infinite image browsing db basic info get o k response has a 5xx status code
func (o *GetDbBasicInfoInfiniteImageBrowsingDbBasicInfoGetOK) IsServerError() bool {
	return false
}

// IsCode returns true when this get db basic info infinite image browsing db basic info get o k response a status code equal to that given
func (o *GetDbBasicInfoInfiniteImageBrowsingDbBasicInfoGetOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the get db basic info infinite image browsing db basic info get o k response
func (o *GetDbBasicInfoInfiniteImageBrowsingDbBasicInfoGetOK) Code() int {
	return 200
}

func (o *GetDbBasicInfoInfiniteImageBrowsingDbBasicInfoGetOK) Error() string {
	return fmt.Sprintf("[GET /infinite_image_browsing/db/basic_info][%d] getDbBasicInfoInfiniteImageBrowsingDbBasicInfoGetOK  %+v", 200, o.Payload)
}

func (o *GetDbBasicInfoInfiniteImageBrowsingDbBasicInfoGetOK) String() string {
	return fmt.Sprintf("[GET /infinite_image_browsing/db/basic_info][%d] getDbBasicInfoInfiniteImageBrowsingDbBasicInfoGetOK  %+v", 200, o.Payload)
}

func (o *GetDbBasicInfoInfiniteImageBrowsingDbBasicInfoGetOK) GetPayload() interface{} {
	return o.Payload
}

func (o *GetDbBasicInfoInfiniteImageBrowsingDbBasicInfoGetOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
