// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewGetDbExpiredInfiniteImageBrowsingDbExpiredDirsGetParams creates a new GetDbExpiredInfiniteImageBrowsingDbExpiredDirsGetParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewGetDbExpiredInfiniteImageBrowsingDbExpiredDirsGetParams() *GetDbExpiredInfiniteImageBrowsingDbExpiredDirsGetParams {
	return &GetDbExpiredInfiniteImageBrowsingDbExpiredDirsGetParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewGetDbExpiredInfiniteImageBrowsingDbExpiredDirsGetParamsWithTimeout creates a new GetDbExpiredInfiniteImageBrowsingDbExpiredDirsGetParams object
// with the ability to set a timeout on a request.
func NewGetDbExpiredInfiniteImageBrowsingDbExpiredDirsGetParamsWithTimeout(timeout time.Duration) *GetDbExpiredInfiniteImageBrowsingDbExpiredDirsGetParams {
	return &GetDbExpiredInfiniteImageBrowsingDbExpiredDirsGetParams{
		timeout: timeout,
	}
}

// NewGetDbExpiredInfiniteImageBrowsingDbExpiredDirsGetParamsWithContext creates a new GetDbExpiredInfiniteImageBrowsingDbExpiredDirsGetParams object
// with the ability to set a context for a request.
func NewGetDbExpiredInfiniteImageBrowsingDbExpiredDirsGetParamsWithContext(ctx context.Context) *GetDbExpiredInfiniteImageBrowsingDbExpiredDirsGetParams {
	return &GetDbExpiredInfiniteImageBrowsingDbExpiredDirsGetParams{
		Context: ctx,
	}
}

// NewGetDbExpiredInfiniteImageBrowsingDbExpiredDirsGetParamsWithHTTPClient creates a new GetDbExpiredInfiniteImageBrowsingDbExpiredDirsGetParams object
// with the ability to set a custom HTTPClient for a request.
func NewGetDbExpiredInfiniteImageBrowsingDbExpiredDirsGetParamsWithHTTPClient(client *http.Client) *GetDbExpiredInfiniteImageBrowsingDbExpiredDirsGetParams {
	return &GetDbExpiredInfiniteImageBrowsingDbExpiredDirsGetParams{
		HTTPClient: client,
	}
}

/*
GetDbExpiredInfiniteImageBrowsingDbExpiredDirsGetParams contains all the parameters to send to the API endpoint

	for the get db expired infinite image browsing db expired dirs get operation.

	Typically these are written to a http.Request.
*/
type GetDbExpiredInfiniteImageBrowsingDbExpiredDirsGetParams struct {
	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the get db expired infinite image browsing db expired dirs get params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetDbExpiredInfiniteImageBrowsingDbExpiredDirsGetParams) WithDefaults() *GetDbExpiredInfiniteImageBrowsingDbExpiredDirsGetParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the get db expired infinite image browsing db expired dirs get params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetDbExpiredInfiniteImageBrowsingDbExpiredDirsGetParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the get db expired infinite image browsing db expired dirs get params
func (o *GetDbExpiredInfiniteImageBrowsingDbExpiredDirsGetParams) WithTimeout(timeout time.Duration) *GetDbExpiredInfiniteImageBrowsingDbExpiredDirsGetParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get db expired infinite image browsing db expired dirs get params
func (o *GetDbExpiredInfiniteImageBrowsingDbExpiredDirsGetParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get db expired infinite image browsing db expired dirs get params
func (o *GetDbExpiredInfiniteImageBrowsingDbExpiredDirsGetParams) WithContext(ctx context.Context) *GetDbExpiredInfiniteImageBrowsingDbExpiredDirsGetParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get db expired infinite image browsing db expired dirs get params
func (o *GetDbExpiredInfiniteImageBrowsingDbExpiredDirsGetParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get db expired infinite image browsing db expired dirs get params
func (o *GetDbExpiredInfiniteImageBrowsingDbExpiredDirsGetParams) WithHTTPClient(client *http.Client) *GetDbExpiredInfiniteImageBrowsingDbExpiredDirsGetParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get db expired infinite image browsing db expired dirs get params
func (o *GetDbExpiredInfiniteImageBrowsingDbExpiredDirsGetParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WriteToRequest writes these params to a swagger request
func (o *GetDbExpiredInfiniteImageBrowsingDbExpiredDirsGetParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
