// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewGetTargetFloderFilesInfiniteImageBrowsingFilesGetParams creates a new GetTargetFloderFilesInfiniteImageBrowsingFilesGetParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewGetTargetFloderFilesInfiniteImageBrowsingFilesGetParams() *GetTargetFloderFilesInfiniteImageBrowsingFilesGetParams {
	return &GetTargetFloderFilesInfiniteImageBrowsingFilesGetParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewGetTargetFloderFilesInfiniteImageBrowsingFilesGetParamsWithTimeout creates a new GetTargetFloderFilesInfiniteImageBrowsingFilesGetParams object
// with the ability to set a timeout on a request.
func NewGetTargetFloderFilesInfiniteImageBrowsingFilesGetParamsWithTimeout(timeout time.Duration) *GetTargetFloderFilesInfiniteImageBrowsingFilesGetParams {
	return &GetTargetFloderFilesInfiniteImageBrowsingFilesGetParams{
		timeout: timeout,
	}
}

// NewGetTargetFloderFilesInfiniteImageBrowsingFilesGetParamsWithContext creates a new GetTargetFloderFilesInfiniteImageBrowsingFilesGetParams object
// with the ability to set a context for a request.
func NewGetTargetFloderFilesInfiniteImageBrowsingFilesGetParamsWithContext(ctx context.Context) *GetTargetFloderFilesInfiniteImageBrowsingFilesGetParams {
	return &GetTargetFloderFilesInfiniteImageBrowsingFilesGetParams{
		Context: ctx,
	}
}

// NewGetTargetFloderFilesInfiniteImageBrowsingFilesGetParamsWithHTTPClient creates a new GetTargetFloderFilesInfiniteImageBrowsingFilesGetParams object
// with the ability to set a custom HTTPClient for a request.
func NewGetTargetFloderFilesInfiniteImageBrowsingFilesGetParamsWithHTTPClient(client *http.Client) *GetTargetFloderFilesInfiniteImageBrowsingFilesGetParams {
	return &GetTargetFloderFilesInfiniteImageBrowsingFilesGetParams{
		HTTPClient: client,
	}
}

/*
GetTargetFloderFilesInfiniteImageBrowsingFilesGetParams contains all the parameters to send to the API endpoint

	for the get target floder files infinite image browsing files get operation.

	Typically these are written to a http.Request.
*/
type GetTargetFloderFilesInfiniteImageBrowsingFilesGetParams struct {

	// FolderPath.
	FolderPath string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the get target floder files infinite image browsing files get params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetTargetFloderFilesInfiniteImageBrowsingFilesGetParams) WithDefaults() *GetTargetFloderFilesInfiniteImageBrowsingFilesGetParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the get target floder files infinite image browsing files get params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetTargetFloderFilesInfiniteImageBrowsingFilesGetParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the get target floder files infinite image browsing files get params
func (o *GetTargetFloderFilesInfiniteImageBrowsingFilesGetParams) WithTimeout(timeout time.Duration) *GetTargetFloderFilesInfiniteImageBrowsingFilesGetParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get target floder files infinite image browsing files get params
func (o *GetTargetFloderFilesInfiniteImageBrowsingFilesGetParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get target floder files infinite image browsing files get params
func (o *GetTargetFloderFilesInfiniteImageBrowsingFilesGetParams) WithContext(ctx context.Context) *GetTargetFloderFilesInfiniteImageBrowsingFilesGetParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get target floder files infinite image browsing files get params
func (o *GetTargetFloderFilesInfiniteImageBrowsingFilesGetParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get target floder files infinite image browsing files get params
func (o *GetTargetFloderFilesInfiniteImageBrowsingFilesGetParams) WithHTTPClient(client *http.Client) *GetTargetFloderFilesInfiniteImageBrowsingFilesGetParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get target floder files infinite image browsing files get params
func (o *GetTargetFloderFilesInfiniteImageBrowsingFilesGetParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithFolderPath adds the folderPath to the get target floder files infinite image browsing files get params
func (o *GetTargetFloderFilesInfiniteImageBrowsingFilesGetParams) WithFolderPath(folderPath string) *GetTargetFloderFilesInfiniteImageBrowsingFilesGetParams {
	o.SetFolderPath(folderPath)
	return o
}

// SetFolderPath adds the folderPath to the get target floder files infinite image browsing files get params
func (o *GetTargetFloderFilesInfiniteImageBrowsingFilesGetParams) SetFolderPath(folderPath string) {
	o.FolderPath = folderPath
}

// WriteToRequest writes these params to a swagger request
func (o *GetTargetFloderFilesInfiniteImageBrowsingFilesGetParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// query param folder_path
	qrFolderPath := o.FolderPath
	qFolderPath := qrFolderPath
	if qFolderPath != "" {

		if err := r.SetQueryParam("folder_path", qFolderPath); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
