// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewGetSdVaesSdapiV1SdVaeGetParams creates a new GetSdVaesSdapiV1SdVaeGetParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewGetSdVaesSdapiV1SdVaeGetParams() *GetSdVaesSdapiV1SdVaeGetParams {
	return &GetSdVaesSdapiV1SdVaeGetParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewGetSdVaesSdapiV1SdVaeGetParamsWithTimeout creates a new GetSdVaesSdapiV1SdVaeGetParams object
// with the ability to set a timeout on a request.
func NewGetSdVaesSdapiV1SdVaeGetParamsWithTimeout(timeout time.Duration) *GetSdVaesSdapiV1SdVaeGetParams {
	return &GetSdVaesSdapiV1SdVaeGetParams{
		timeout: timeout,
	}
}

// NewGetSdVaesSdapiV1SdVaeGetParamsWithContext creates a new GetSdVaesSdapiV1SdVaeGetParams object
// with the ability to set a context for a request.
func NewGetSdVaesSdapiV1SdVaeGetParamsWithContext(ctx context.Context) *GetSdVaesSdapiV1SdVaeGetParams {
	return &GetSdVaesSdapiV1SdVaeGetParams{
		Context: ctx,
	}
}

// NewGetSdVaesSdapiV1SdVaeGetParamsWithHTTPClient creates a new GetSdVaesSdapiV1SdVaeGetParams object
// with the ability to set a custom HTTPClient for a request.
func NewGetSdVaesSdapiV1SdVaeGetParamsWithHTTPClient(client *http.Client) *GetSdVaesSdapiV1SdVaeGetParams {
	return &GetSdVaesSdapiV1SdVaeGetParams{
		HTTPClient: client,
	}
}

/*
GetSdVaesSdapiV1SdVaeGetParams contains all the parameters to send to the API endpoint

	for the get sd vaes sdapi v1 sd vae get operation.

	Typically these are written to a http.Request.
*/
type GetSdVaesSdapiV1SdVaeGetParams struct {
	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the get sd vaes sdapi v1 sd vae get params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetSdVaesSdapiV1SdVaeGetParams) WithDefaults() *GetSdVaesSdapiV1SdVaeGetParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the get sd vaes sdapi v1 sd vae get params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetSdVaesSdapiV1SdVaeGetParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the get sd vaes sdapi v1 sd vae get params
func (o *GetSdVaesSdapiV1SdVaeGetParams) WithTimeout(timeout time.Duration) *GetSdVaesSdapiV1SdVaeGetParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get sd vaes sdapi v1 sd vae get params
func (o *GetSdVaesSdapiV1SdVaeGetParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get sd vaes sdapi v1 sd vae get params
func (o *GetSdVaesSdapiV1SdVaeGetParams) WithContext(ctx context.Context) *GetSdVaesSdapiV1SdVaeGetParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get sd vaes sdapi v1 sd vae get params
func (o *GetSdVaesSdapiV1SdVaeGetParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get sd vaes sdapi v1 sd vae get params
func (o *GetSdVaesSdapiV1SdVaeGetParams) WithHTTPClient(client *http.Client) *GetSdVaesSdapiV1SdVaeGetParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get sd vaes sdapi v1 sd vae get params
func (o *GetSdVaesSdapiV1SdVaeGetParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WriteToRequest writes these params to a swagger request
func (o *GetSdVaesSdapiV1SdVaeGetParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
