// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// GlobalSettingInfiniteImageBrowsingGlobalSettingGetReader is a Reader for the GlobalSettingInfiniteImageBrowsingGlobalSettingGet structure.
type GlobalSettingInfiniteImageBrowsingGlobalSettingGetReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GlobalSettingInfiniteImageBrowsingGlobalSettingGetReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGlobalSettingInfiniteImageBrowsingGlobalSettingGetOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewGlobalSettingInfiniteImageBrowsingGlobalSettingGetOK creates a GlobalSettingInfiniteImageBrowsingGlobalSettingGetOK with default headers values
func NewGlobalSettingInfiniteImageBrowsingGlobalSettingGetOK() *GlobalSettingInfiniteImageBrowsingGlobalSettingGetOK {
	return &GlobalSettingInfiniteImageBrowsingGlobalSettingGetOK{}
}

/*
GlobalSettingInfiniteImageBrowsingGlobalSettingGetOK describes a response with status code 200, with default header values.

Successful Response
*/
type GlobalSettingInfiniteImageBrowsingGlobalSettingGetOK struct {
	Payload interface{}
}

// IsSuccess returns true when this global setting infinite image browsing global setting get o k response has a 2xx status code
func (o *GlobalSettingInfiniteImageBrowsingGlobalSettingGetOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this global setting infinite image browsing global setting get o k response has a 3xx status code
func (o *GlobalSettingInfiniteImageBrowsingGlobalSettingGetOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this global setting infinite image browsing global setting get o k response has a 4xx status code
func (o *GlobalSettingInfiniteImageBrowsingGlobalSettingGetOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this global setting infinite image browsing global setting get o k response has a 5xx status code
func (o *GlobalSettingInfiniteImageBrowsingGlobalSettingGetOK) IsServerError() bool {
	return false
}

// IsCode returns true when this global setting infinite image browsing global setting get o k response a status code equal to that given
func (o *GlobalSettingInfiniteImageBrowsingGlobalSettingGetOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the global setting infinite image browsing global setting get o k response
func (o *GlobalSettingInfiniteImageBrowsingGlobalSettingGetOK) Code() int {
	return 200
}

func (o *GlobalSettingInfiniteImageBrowsingGlobalSettingGetOK) Error() string {
	return fmt.Sprintf("[GET /infinite_image_browsing/global_setting][%d] globalSettingInfiniteImageBrowsingGlobalSettingGetOK  %+v", 200, o.Payload)
}

func (o *GlobalSettingInfiniteImageBrowsingGlobalSettingGetOK) String() string {
	return fmt.Sprintf("[GET /infinite_image_browsing/global_setting][%d] globalSettingInfiniteImageBrowsingGlobalSettingGetOK  %+v", 200, o.Payload)
}

func (o *GlobalSettingInfiniteImageBrowsingGlobalSettingGetOK) GetPayload() interface{} {
	return o.Payload
}

func (o *GlobalSettingInfiniteImageBrowsingGlobalSettingGetOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
