// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewImageGeninfoInfiniteImageBrowsingImageGeninfoGetParams creates a new ImageGeninfoInfiniteImageBrowsingImageGeninfoGetParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewImageGeninfoInfiniteImageBrowsingImageGeninfoGetParams() *ImageGeninfoInfiniteImageBrowsingImageGeninfoGetParams {
	return &ImageGeninfoInfiniteImageBrowsingImageGeninfoGetParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewImageGeninfoInfiniteImageBrowsingImageGeninfoGetParamsWithTimeout creates a new ImageGeninfoInfiniteImageBrowsingImageGeninfoGetParams object
// with the ability to set a timeout on a request.
func NewImageGeninfoInfiniteImageBrowsingImageGeninfoGetParamsWithTimeout(timeout time.Duration) *ImageGeninfoInfiniteImageBrowsingImageGeninfoGetParams {
	return &ImageGeninfoInfiniteImageBrowsingImageGeninfoGetParams{
		timeout: timeout,
	}
}

// NewImageGeninfoInfiniteImageBrowsingImageGeninfoGetParamsWithContext creates a new ImageGeninfoInfiniteImageBrowsingImageGeninfoGetParams object
// with the ability to set a context for a request.
func NewImageGeninfoInfiniteImageBrowsingImageGeninfoGetParamsWithContext(ctx context.Context) *ImageGeninfoInfiniteImageBrowsingImageGeninfoGetParams {
	return &ImageGeninfoInfiniteImageBrowsingImageGeninfoGetParams{
		Context: ctx,
	}
}

// NewImageGeninfoInfiniteImageBrowsingImageGeninfoGetParamsWithHTTPClient creates a new ImageGeninfoInfiniteImageBrowsingImageGeninfoGetParams object
// with the ability to set a custom HTTPClient for a request.
func NewImageGeninfoInfiniteImageBrowsingImageGeninfoGetParamsWithHTTPClient(client *http.Client) *ImageGeninfoInfiniteImageBrowsingImageGeninfoGetParams {
	return &ImageGeninfoInfiniteImageBrowsingImageGeninfoGetParams{
		HTTPClient: client,
	}
}

/*
ImageGeninfoInfiniteImageBrowsingImageGeninfoGetParams contains all the parameters to send to the API endpoint

	for the image geninfo infinite image browsing image geninfo get operation.

	Typically these are written to a http.Request.
*/
type ImageGeninfoInfiniteImageBrowsingImageGeninfoGetParams struct {

	// Path.
	Path string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the image geninfo infinite image browsing image geninfo get params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *ImageGeninfoInfiniteImageBrowsingImageGeninfoGetParams) WithDefaults() *ImageGeninfoInfiniteImageBrowsingImageGeninfoGetParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the image geninfo infinite image browsing image geninfo get params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *ImageGeninfoInfiniteImageBrowsingImageGeninfoGetParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the image geninfo infinite image browsing image geninfo get params
func (o *ImageGeninfoInfiniteImageBrowsingImageGeninfoGetParams) WithTimeout(timeout time.Duration) *ImageGeninfoInfiniteImageBrowsingImageGeninfoGetParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the image geninfo infinite image browsing image geninfo get params
func (o *ImageGeninfoInfiniteImageBrowsingImageGeninfoGetParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the image geninfo infinite image browsing image geninfo get params
func (o *ImageGeninfoInfiniteImageBrowsingImageGeninfoGetParams) WithContext(ctx context.Context) *ImageGeninfoInfiniteImageBrowsingImageGeninfoGetParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the image geninfo infinite image browsing image geninfo get params
func (o *ImageGeninfoInfiniteImageBrowsingImageGeninfoGetParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the image geninfo infinite image browsing image geninfo get params
func (o *ImageGeninfoInfiniteImageBrowsingImageGeninfoGetParams) WithHTTPClient(client *http.Client) *ImageGeninfoInfiniteImageBrowsingImageGeninfoGetParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the image geninfo infinite image browsing image geninfo get params
func (o *ImageGeninfoInfiniteImageBrowsingImageGeninfoGetParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithPath adds the path to the image geninfo infinite image browsing image geninfo get params
func (o *ImageGeninfoInfiniteImageBrowsingImageGeninfoGetParams) WithPath(path string) *ImageGeninfoInfiniteImageBrowsingImageGeninfoGetParams {
	o.SetPath(path)
	return o
}

// SetPath adds the path to the image geninfo infinite image browsing image geninfo get params
func (o *ImageGeninfoInfiniteImageBrowsingImageGeninfoGetParams) SetPath(path string) {
	o.Path = path
}

// WriteToRequest writes these params to a swagger request
func (o *ImageGeninfoInfiniteImageBrowsingImageGeninfoGetParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// query param path
	qrPath := o.Path
	qPath := qrPath
	if qPath != "" {

		if err := r.SetQueryParam("path", qPath); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
