// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// LambdaInternalPingGetReader is a Reader for the LambdaInternalPingGet structure.
type LambdaInternalPingGetReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *LambdaInternalPingGetReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewLambdaInternalPingGetOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewLambdaInternalPingGetOK creates a LambdaInternalPingGetOK with default headers values
func NewLambdaInternalPingGetOK() *LambdaInternalPingGetOK {
	return &LambdaInternalPingGetOK{}
}

/*
LambdaInternalPingGetOK describes a response with status code 200, with default header values.

Successful Response
*/
type LambdaInternalPingGetOK struct {
	Payload interface{}
}

// IsSuccess returns true when this lambda internal ping get o k response has a 2xx status code
func (o *LambdaInternalPingGetOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this lambda internal ping get o k response has a 3xx status code
func (o *LambdaInternalPingGetOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this lambda internal ping get o k response has a 4xx status code
func (o *LambdaInternalPingGetOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this lambda internal ping get o k response has a 5xx status code
func (o *LambdaInternalPingGetOK) IsServerError() bool {
	return false
}

// IsCode returns true when this lambda internal ping get o k response a status code equal to that given
func (o *LambdaInternalPingGetOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the lambda internal ping get o k response
func (o *LambdaInternalPingGetOK) Code() int {
	return 200
}

func (o *LambdaInternalPingGetOK) Error() string {
	return fmt.Sprintf("[GET /internal/ping][%d] lambdaInternalPingGetOK  %+v", 200, o.Payload)
}

func (o *LambdaInternalPingGetOK) String() string {
	return fmt.Sprintf("[GET /internal/ping][%d] lambdaInternalPingGetOK  %+v", 200, o.Payload)
}

func (o *LambdaInternalPingGetOK) GetPayload() interface{} {
	return o.Payload
}

func (o *LambdaInternalPingGetOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
