// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewLoginCheckLoginCheckGetParams creates a new LoginCheckLoginCheckGetParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewLoginCheckLoginCheckGetParams() *LoginCheckLoginCheckGetParams {
	return &LoginCheckLoginCheckGetParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewLoginCheckLoginCheckGetParamsWithTimeout creates a new LoginCheckLoginCheckGetParams object
// with the ability to set a timeout on a request.
func NewLoginCheckLoginCheckGetParamsWithTimeout(timeout time.Duration) *LoginCheckLoginCheckGetParams {
	return &LoginCheckLoginCheckGetParams{
		timeout: timeout,
	}
}

// NewLoginCheckLoginCheckGetParamsWithContext creates a new LoginCheckLoginCheckGetParams object
// with the ability to set a context for a request.
func NewLoginCheckLoginCheckGetParamsWithContext(ctx context.Context) *LoginCheckLoginCheckGetParams {
	return &LoginCheckLoginCheckGetParams{
		Context: ctx,
	}
}

// NewLoginCheckLoginCheckGetParamsWithHTTPClient creates a new LoginCheckLoginCheckGetParams object
// with the ability to set a custom HTTPClient for a request.
func NewLoginCheckLoginCheckGetParamsWithHTTPClient(client *http.Client) *LoginCheckLoginCheckGetParams {
	return &LoginCheckLoginCheckGetParams{
		HTTPClient: client,
	}
}

/*
LoginCheckLoginCheckGetParams contains all the parameters to send to the API endpoint

	for the login check login check get operation.

	Typically these are written to a http.Request.
*/
type LoginCheckLoginCheckGetParams struct {
	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the login check login check get params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *LoginCheckLoginCheckGetParams) WithDefaults() *LoginCheckLoginCheckGetParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the login check login check get params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *LoginCheckLoginCheckGetParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the login check login check get params
func (o *LoginCheckLoginCheckGetParams) WithTimeout(timeout time.Duration) *LoginCheckLoginCheckGetParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the login check login check get params
func (o *LoginCheckLoginCheckGetParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the login check login check get params
func (o *LoginCheckLoginCheckGetParams) WithContext(ctx context.Context) *LoginCheckLoginCheckGetParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the login check login check get params
func (o *LoginCheckLoginCheckGetParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the login check login check get params
func (o *LoginCheckLoginCheckGetParams) WithHTTPClient(client *http.Client) *LoginCheckLoginCheckGetParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the login check login check get params
func (o *LoginCheckLoginCheckGetParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WriteToRequest writes these params to a swagger request
func (o *LoginCheckLoginCheckGetParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
