// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewMainHeadParams creates a new MainHeadParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewMainHeadParams() *MainHeadParams {
	return &MainHeadParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewMainHeadParamsWithTimeout creates a new MainHeadParams object
// with the ability to set a timeout on a request.
func NewMainHeadParamsWithTimeout(timeout time.Duration) *MainHeadParams {
	return &MainHeadParams{
		timeout: timeout,
	}
}

// NewMainHeadParamsWithContext creates a new MainHeadParams object
// with the ability to set a context for a request.
func NewMainHeadParamsWithContext(ctx context.Context) *MainHeadParams {
	return &MainHeadParams{
		Context: ctx,
	}
}

// NewMainHeadParamsWithHTTPClient creates a new MainHeadParams object
// with the ability to set a custom HTTPClient for a request.
func NewMainHeadParamsWithHTTPClient(client *http.Client) *MainHeadParams {
	return &MainHeadParams{
		HTTPClient: client,
	}
}

/*
MainHeadParams contains all the parameters to send to the API endpoint

	for the main head operation.

	Typically these are written to a http.Request.
*/
type MainHeadParams struct {
	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the main head params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *MainHeadParams) WithDefaults() *MainHeadParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the main head params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *MainHeadParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the main head params
func (o *MainHeadParams) WithTimeout(timeout time.Duration) *MainHeadParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the main head params
func (o *MainHeadParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the main head params
func (o *MainHeadParams) WithContext(ctx context.Context) *MainHeadParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the main head params
func (o *MainHeadParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the main head params
func (o *MainHeadParams) WithHTTPClient(client *http.Client) *MainHeadParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the main head params
func (o *MainHeadParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WriteToRequest writes these params to a swagger request
func (o *MainHeadParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
