// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/SpenserCai/sd-webui-go/stablediffusion/models"
)

// MoveFilesInfiniteImageBrowsingMoveFilesPostReader is a Reader for the MoveFilesInfiniteImageBrowsingMoveFilesPost structure.
type MoveFilesInfiniteImageBrowsingMoveFilesPostReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *MoveFilesInfiniteImageBrowsingMoveFilesPostReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewMoveFilesInfiniteImageBrowsingMoveFilesPostOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 422:
		result := NewMoveFilesInfiniteImageBrowsingMoveFilesPostUnprocessableEntity()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewMoveFilesInfiniteImageBrowsingMoveFilesPostOK creates a MoveFilesInfiniteImageBrowsingMoveFilesPostOK with default headers values
func NewMoveFilesInfiniteImageBrowsingMoveFilesPostOK() *MoveFilesInfiniteImageBrowsingMoveFilesPostOK {
	return &MoveFilesInfiniteImageBrowsingMoveFilesPostOK{}
}

/*
MoveFilesInfiniteImageBrowsingMoveFilesPostOK describes a response with status code 200, with default header values.

Successful Response
*/
type MoveFilesInfiniteImageBrowsingMoveFilesPostOK struct {
	Payload interface{}
}

// IsSuccess returns true when this move files infinite image browsing move files post o k response has a 2xx status code
func (o *MoveFilesInfiniteImageBrowsingMoveFilesPostOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this move files infinite image browsing move files post o k response has a 3xx status code
func (o *MoveFilesInfiniteImageBrowsingMoveFilesPostOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this move files infinite image browsing move files post o k response has a 4xx status code
func (o *MoveFilesInfiniteImageBrowsingMoveFilesPostOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this move files infinite image browsing move files post o k response has a 5xx status code
func (o *MoveFilesInfiniteImageBrowsingMoveFilesPostOK) IsServerError() bool {
	return false
}

// IsCode returns true when this move files infinite image browsing move files post o k response a status code equal to that given
func (o *MoveFilesInfiniteImageBrowsingMoveFilesPostOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the move files infinite image browsing move files post o k response
func (o *MoveFilesInfiniteImageBrowsingMoveFilesPostOK) Code() int {
	return 200
}

func (o *MoveFilesInfiniteImageBrowsingMoveFilesPostOK) Error() string {
	return fmt.Sprintf("[POST /infinite_image_browsing/move_files][%d] moveFilesInfiniteImageBrowsingMoveFilesPostOK  %+v", 200, o.Payload)
}

func (o *MoveFilesInfiniteImageBrowsingMoveFilesPostOK) String() string {
	return fmt.Sprintf("[POST /infinite_image_browsing/move_files][%d] moveFilesInfiniteImageBrowsingMoveFilesPostOK  %+v", 200, o.Payload)
}

func (o *MoveFilesInfiniteImageBrowsingMoveFilesPostOK) GetPayload() interface{} {
	return o.Payload
}

func (o *MoveFilesInfiniteImageBrowsingMoveFilesPostOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewMoveFilesInfiniteImageBrowsingMoveFilesPostUnprocessableEntity creates a MoveFilesInfiniteImageBrowsingMoveFilesPostUnprocessableEntity with default headers values
func NewMoveFilesInfiniteImageBrowsingMoveFilesPostUnprocessableEntity() *MoveFilesInfiniteImageBrowsingMoveFilesPostUnprocessableEntity {
	return &MoveFilesInfiniteImageBrowsingMoveFilesPostUnprocessableEntity{}
}

/*
MoveFilesInfiniteImageBrowsingMoveFilesPostUnprocessableEntity describes a response with status code 422, with default header values.

Validation Error
*/
type MoveFilesInfiniteImageBrowsingMoveFilesPostUnprocessableEntity struct {
	Payload *models.HTTPValidationError
}

// IsSuccess returns true when this move files infinite image browsing move files post unprocessable entity response has a 2xx status code
func (o *MoveFilesInfiniteImageBrowsingMoveFilesPostUnprocessableEntity) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this move files infinite image browsing move files post unprocessable entity response has a 3xx status code
func (o *MoveFilesInfiniteImageBrowsingMoveFilesPostUnprocessableEntity) IsRedirect() bool {
	return false
}

// IsClientError returns true when this move files infinite image browsing move files post unprocessable entity response has a 4xx status code
func (o *MoveFilesInfiniteImageBrowsingMoveFilesPostUnprocessableEntity) IsClientError() bool {
	return true
}

// IsServerError returns true when this move files infinite image browsing move files post unprocessable entity response has a 5xx status code
func (o *MoveFilesInfiniteImageBrowsingMoveFilesPostUnprocessableEntity) IsServerError() bool {
	return false
}

// IsCode returns true when this move files infinite image browsing move files post unprocessable entity response a status code equal to that given
func (o *MoveFilesInfiniteImageBrowsingMoveFilesPostUnprocessableEntity) IsCode(code int) bool {
	return code == 422
}

// Code gets the status code for the move files infinite image browsing move files post unprocessable entity response
func (o *MoveFilesInfiniteImageBrowsingMoveFilesPostUnprocessableEntity) Code() int {
	return 422
}

func (o *MoveFilesInfiniteImageBrowsingMoveFilesPostUnprocessableEntity) Error() string {
	return fmt.Sprintf("[POST /infinite_image_browsing/move_files][%d] moveFilesInfiniteImageBrowsingMoveFilesPostUnprocessableEntity  %+v", 422, o.Payload)
}

func (o *MoveFilesInfiniteImageBrowsingMoveFilesPostUnprocessableEntity) String() string {
	return fmt.Sprintf("[POST /infinite_image_browsing/move_files][%d] moveFilesInfiniteImageBrowsingMoveFilesPostUnprocessableEntity  %+v", 422, o.Payload)
}

func (o *MoveFilesInfiniteImageBrowsingMoveFilesPostUnprocessableEntity) GetPayload() *models.HTTPValidationError {
	return o.Payload
}

func (o *MoveFilesInfiniteImageBrowsingMoveFilesPostUnprocessableEntity) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.HTTPValidationError)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
