// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/SpenserCai/sd-webui-go/stablediffusion/models"
)

// ProgressapiInternalProgressPostReader is a Reader for the ProgressapiInternalProgressPost structure.
type ProgressapiInternalProgressPostReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *ProgressapiInternalProgressPostReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewProgressapiInternalProgressPostOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 422:
		result := NewProgressapiInternalProgressPostUnprocessableEntity()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewProgressapiInternalProgressPostInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewProgressapiInternalProgressPostOK creates a ProgressapiInternalProgressPostOK with default headers values
func NewProgressapiInternalProgressPostOK() *ProgressapiInternalProgressPostOK {
	return &ProgressapiInternalProgressPostOK{}
}

/*
ProgressapiInternalProgressPostOK describes a response with status code 200, with default header values.

Successful Response
*/
type ProgressapiInternalProgressPostOK struct {
	Payload *models.ModulesProgressProgressResponse
}

// IsSuccess returns true when this progressapi internal progress post o k response has a 2xx status code
func (o *ProgressapiInternalProgressPostOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this progressapi internal progress post o k response has a 3xx status code
func (o *ProgressapiInternalProgressPostOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this progressapi internal progress post o k response has a 4xx status code
func (o *ProgressapiInternalProgressPostOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this progressapi internal progress post o k response has a 5xx status code
func (o *ProgressapiInternalProgressPostOK) IsServerError() bool {
	return false
}

// IsCode returns true when this progressapi internal progress post o k response a status code equal to that given
func (o *ProgressapiInternalProgressPostOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the progressapi internal progress post o k response
func (o *ProgressapiInternalProgressPostOK) Code() int {
	return 200
}

func (o *ProgressapiInternalProgressPostOK) Error() string {
	return fmt.Sprintf("[POST /internal/progress][%d] progressapiInternalProgressPostOK  %+v", 200, o.Payload)
}

func (o *ProgressapiInternalProgressPostOK) String() string {
	return fmt.Sprintf("[POST /internal/progress][%d] progressapiInternalProgressPostOK  %+v", 200, o.Payload)
}

func (o *ProgressapiInternalProgressPostOK) GetPayload() *models.ModulesProgressProgressResponse {
	return o.Payload
}

func (o *ProgressapiInternalProgressPostOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ModulesProgressProgressResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewProgressapiInternalProgressPostUnprocessableEntity creates a ProgressapiInternalProgressPostUnprocessableEntity with default headers values
func NewProgressapiInternalProgressPostUnprocessableEntity() *ProgressapiInternalProgressPostUnprocessableEntity {
	return &ProgressapiInternalProgressPostUnprocessableEntity{}
}

/*
ProgressapiInternalProgressPostUnprocessableEntity describes a response with status code 422, with default header values.

Validation Error
*/
type ProgressapiInternalProgressPostUnprocessableEntity struct {
	Payload *models.HTTPValidationError
}

// IsSuccess returns true when this progressapi internal progress post unprocessable entity response has a 2xx status code
func (o *ProgressapiInternalProgressPostUnprocessableEntity) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this progressapi internal progress post unprocessable entity response has a 3xx status code
func (o *ProgressapiInternalProgressPostUnprocessableEntity) IsRedirect() bool {
	return false
}

// IsClientError returns true when this progressapi internal progress post unprocessable entity response has a 4xx status code
func (o *ProgressapiInternalProgressPostUnprocessableEntity) IsClientError() bool {
	return true
}

// IsServerError returns true when this progressapi internal progress post unprocessable entity response has a 5xx status code
func (o *ProgressapiInternalProgressPostUnprocessableEntity) IsServerError() bool {
	return false
}

// IsCode returns true when this progressapi internal progress post unprocessable entity response a status code equal to that given
func (o *ProgressapiInternalProgressPostUnprocessableEntity) IsCode(code int) bool {
	return code == 422
}

// Code gets the status code for the progressapi internal progress post unprocessable entity response
func (o *ProgressapiInternalProgressPostUnprocessableEntity) Code() int {
	return 422
}

func (o *ProgressapiInternalProgressPostUnprocessableEntity) Error() string {
	return fmt.Sprintf("[POST /internal/progress][%d] progressapiInternalProgressPostUnprocessableEntity  %+v", 422, o.Payload)
}

func (o *ProgressapiInternalProgressPostUnprocessableEntity) String() string {
	return fmt.Sprintf("[POST /internal/progress][%d] progressapiInternalProgressPostUnprocessableEntity  %+v", 422, o.Payload)
}

func (o *ProgressapiInternalProgressPostUnprocessableEntity) GetPayload() *models.HTTPValidationError {
	return o.Payload
}

func (o *ProgressapiInternalProgressPostUnprocessableEntity) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.HTTPValidationError)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewProgressapiInternalProgressPostInternalServerError creates a ProgressapiInternalProgressPostInternalServerError with default headers values
func NewProgressapiInternalProgressPostInternalServerError() *ProgressapiInternalProgressPostInternalServerError {
	return &ProgressapiInternalProgressPostInternalServerError{}
}

/*
ProgressapiInternalProgressPostInternalServerError describes a response with status code 500, with default header values.

HTTPException
*/
type ProgressapiInternalProgressPostInternalServerError struct {
	Payload *models.HTTPException
}

// IsSuccess returns true when this progressapi internal progress post internal server error response has a 2xx status code
func (o *ProgressapiInternalProgressPostInternalServerError) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this progressapi internal progress post internal server error response has a 3xx status code
func (o *ProgressapiInternalProgressPostInternalServerError) IsRedirect() bool {
	return false
}

// IsClientError returns true when this progressapi internal progress post internal server error response has a 4xx status code
func (o *ProgressapiInternalProgressPostInternalServerError) IsClientError() bool {
	return false
}

// IsServerError returns true when this progressapi internal progress post internal server error response has a 5xx status code
func (o *ProgressapiInternalProgressPostInternalServerError) IsServerError() bool {
	return true
}

// IsCode returns true when this progressapi internal progress post internal server error response a status code equal to that given
func (o *ProgressapiInternalProgressPostInternalServerError) IsCode(code int) bool {
	return code == 500
}

// Code gets the status code for the progressapi internal progress post internal server error response
func (o *ProgressapiInternalProgressPostInternalServerError) Code() int {
	return 500
}

func (o *ProgressapiInternalProgressPostInternalServerError) Error() string {
	return fmt.Sprintf("[POST /internal/progress][%d] progressapiInternalProgressPostInternalServerError  %+v", 500, o.Payload)
}

func (o *ProgressapiInternalProgressPostInternalServerError) String() string {
	return fmt.Sprintf("[POST /internal/progress][%d] progressapiInternalProgressPostInternalServerError  %+v", 500, o.Payload)
}

func (o *ProgressapiInternalProgressPostInternalServerError) GetPayload() *models.HTTPException {
	return o.Payload
}

func (o *ProgressapiInternalProgressPostInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.HTTPException)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
