// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewQuicksettingsHintInternalQuicksettingsHintGetParams creates a new QuicksettingsHintInternalQuicksettingsHintGetParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewQuicksettingsHintInternalQuicksettingsHintGetParams() *QuicksettingsHintInternalQuicksettingsHintGetParams {
	return &QuicksettingsHintInternalQuicksettingsHintGetParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewQuicksettingsHintInternalQuicksettingsHintGetParamsWithTimeout creates a new QuicksettingsHintInternalQuicksettingsHintGetParams object
// with the ability to set a timeout on a request.
func NewQuicksettingsHintInternalQuicksettingsHintGetParamsWithTimeout(timeout time.Duration) *QuicksettingsHintInternalQuicksettingsHintGetParams {
	return &QuicksettingsHintInternalQuicksettingsHintGetParams{
		timeout: timeout,
	}
}

// NewQuicksettingsHintInternalQuicksettingsHintGetParamsWithContext creates a new QuicksettingsHintInternalQuicksettingsHintGetParams object
// with the ability to set a context for a request.
func NewQuicksettingsHintInternalQuicksettingsHintGetParamsWithContext(ctx context.Context) *QuicksettingsHintInternalQuicksettingsHintGetParams {
	return &QuicksettingsHintInternalQuicksettingsHintGetParams{
		Context: ctx,
	}
}

// NewQuicksettingsHintInternalQuicksettingsHintGetParamsWithHTTPClient creates a new QuicksettingsHintInternalQuicksettingsHintGetParams object
// with the ability to set a custom HTTPClient for a request.
func NewQuicksettingsHintInternalQuicksettingsHintGetParamsWithHTTPClient(client *http.Client) *QuicksettingsHintInternalQuicksettingsHintGetParams {
	return &QuicksettingsHintInternalQuicksettingsHintGetParams{
		HTTPClient: client,
	}
}

/*
QuicksettingsHintInternalQuicksettingsHintGetParams contains all the parameters to send to the API endpoint

	for the quicksettings hint internal quicksettings hint get operation.

	Typically these are written to a http.Request.
*/
type QuicksettingsHintInternalQuicksettingsHintGetParams struct {
	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the quicksettings hint internal quicksettings hint get params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *QuicksettingsHintInternalQuicksettingsHintGetParams) WithDefaults() *QuicksettingsHintInternalQuicksettingsHintGetParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the quicksettings hint internal quicksettings hint get params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *QuicksettingsHintInternalQuicksettingsHintGetParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the quicksettings hint internal quicksettings hint get params
func (o *QuicksettingsHintInternalQuicksettingsHintGetParams) WithTimeout(timeout time.Duration) *QuicksettingsHintInternalQuicksettingsHintGetParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the quicksettings hint internal quicksettings hint get params
func (o *QuicksettingsHintInternalQuicksettingsHintGetParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the quicksettings hint internal quicksettings hint get params
func (o *QuicksettingsHintInternalQuicksettingsHintGetParams) WithContext(ctx context.Context) *QuicksettingsHintInternalQuicksettingsHintGetParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the quicksettings hint internal quicksettings hint get params
func (o *QuicksettingsHintInternalQuicksettingsHintGetParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the quicksettings hint internal quicksettings hint get params
func (o *QuicksettingsHintInternalQuicksettingsHintGetParams) WithHTTPClient(client *http.Client) *QuicksettingsHintInternalQuicksettingsHintGetParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the quicksettings hint internal quicksettings hint get params
func (o *QuicksettingsHintInternalQuicksettingsHintGetParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WriteToRequest writes these params to a swagger request
func (o *QuicksettingsHintInternalQuicksettingsHintGetParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
