// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewRefreshCheckpointsSdapiV1RefreshCheckpointsPostParams creates a new RefreshCheckpointsSdapiV1RefreshCheckpointsPostParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewRefreshCheckpointsSdapiV1RefreshCheckpointsPostParams() *RefreshCheckpointsSdapiV1RefreshCheckpointsPostParams {
	return &RefreshCheckpointsSdapiV1RefreshCheckpointsPostParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewRefreshCheckpointsSdapiV1RefreshCheckpointsPostParamsWithTimeout creates a new RefreshCheckpointsSdapiV1RefreshCheckpointsPostParams object
// with the ability to set a timeout on a request.
func NewRefreshCheckpointsSdapiV1RefreshCheckpointsPostParamsWithTimeout(timeout time.Duration) *RefreshCheckpointsSdapiV1RefreshCheckpointsPostParams {
	return &RefreshCheckpointsSdapiV1RefreshCheckpointsPostParams{
		timeout: timeout,
	}
}

// NewRefreshCheckpointsSdapiV1RefreshCheckpointsPostParamsWithContext creates a new RefreshCheckpointsSdapiV1RefreshCheckpointsPostParams object
// with the ability to set a context for a request.
func NewRefreshCheckpointsSdapiV1RefreshCheckpointsPostParamsWithContext(ctx context.Context) *RefreshCheckpointsSdapiV1RefreshCheckpointsPostParams {
	return &RefreshCheckpointsSdapiV1RefreshCheckpointsPostParams{
		Context: ctx,
	}
}

// NewRefreshCheckpointsSdapiV1RefreshCheckpointsPostParamsWithHTTPClient creates a new RefreshCheckpointsSdapiV1RefreshCheckpointsPostParams object
// with the ability to set a custom HTTPClient for a request.
func NewRefreshCheckpointsSdapiV1RefreshCheckpointsPostParamsWithHTTPClient(client *http.Client) *RefreshCheckpointsSdapiV1RefreshCheckpointsPostParams {
	return &RefreshCheckpointsSdapiV1RefreshCheckpointsPostParams{
		HTTPClient: client,
	}
}

/*
RefreshCheckpointsSdapiV1RefreshCheckpointsPostParams contains all the parameters to send to the API endpoint

	for the refresh checkpoints sdapi v1 refresh checkpoints post operation.

	Typically these are written to a http.Request.
*/
type RefreshCheckpointsSdapiV1RefreshCheckpointsPostParams struct {
	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the refresh checkpoints sdapi v1 refresh checkpoints post params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *RefreshCheckpointsSdapiV1RefreshCheckpointsPostParams) WithDefaults() *RefreshCheckpointsSdapiV1RefreshCheckpointsPostParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the refresh checkpoints sdapi v1 refresh checkpoints post params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *RefreshCheckpointsSdapiV1RefreshCheckpointsPostParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the refresh checkpoints sdapi v1 refresh checkpoints post params
func (o *RefreshCheckpointsSdapiV1RefreshCheckpointsPostParams) WithTimeout(timeout time.Duration) *RefreshCheckpointsSdapiV1RefreshCheckpointsPostParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the refresh checkpoints sdapi v1 refresh checkpoints post params
func (o *RefreshCheckpointsSdapiV1RefreshCheckpointsPostParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the refresh checkpoints sdapi v1 refresh checkpoints post params
func (o *RefreshCheckpointsSdapiV1RefreshCheckpointsPostParams) WithContext(ctx context.Context) *RefreshCheckpointsSdapiV1RefreshCheckpointsPostParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the refresh checkpoints sdapi v1 refresh checkpoints post params
func (o *RefreshCheckpointsSdapiV1RefreshCheckpointsPostParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the refresh checkpoints sdapi v1 refresh checkpoints post params
func (o *RefreshCheckpointsSdapiV1RefreshCheckpointsPostParams) WithHTTPClient(client *http.Client) *RefreshCheckpointsSdapiV1RefreshCheckpointsPostParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the refresh checkpoints sdapi v1 refresh checkpoints post params
func (o *RefreshCheckpointsSdapiV1RefreshCheckpointsPostParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WriteToRequest writes these params to a swagger request
func (o *RefreshCheckpointsSdapiV1RefreshCheckpointsPostParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
