// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewRefreshLorasSdapiV1RefreshLorasPostParams creates a new RefreshLorasSdapiV1RefreshLorasPostParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewRefreshLorasSdapiV1RefreshLorasPostParams() *RefreshLorasSdapiV1RefreshLorasPostParams {
	return &RefreshLorasSdapiV1RefreshLorasPostParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewRefreshLorasSdapiV1RefreshLorasPostParamsWithTimeout creates a new RefreshLorasSdapiV1RefreshLorasPostParams object
// with the ability to set a timeout on a request.
func NewRefreshLorasSdapiV1RefreshLorasPostParamsWithTimeout(timeout time.Duration) *RefreshLorasSdapiV1RefreshLorasPostParams {
	return &RefreshLorasSdapiV1RefreshLorasPostParams{
		timeout: timeout,
	}
}

// NewRefreshLorasSdapiV1RefreshLorasPostParamsWithContext creates a new RefreshLorasSdapiV1RefreshLorasPostParams object
// with the ability to set a context for a request.
func NewRefreshLorasSdapiV1RefreshLorasPostParamsWithContext(ctx context.Context) *RefreshLorasSdapiV1RefreshLorasPostParams {
	return &RefreshLorasSdapiV1RefreshLorasPostParams{
		Context: ctx,
	}
}

// NewRefreshLorasSdapiV1RefreshLorasPostParamsWithHTTPClient creates a new RefreshLorasSdapiV1RefreshLorasPostParams object
// with the ability to set a custom HTTPClient for a request.
func NewRefreshLorasSdapiV1RefreshLorasPostParamsWithHTTPClient(client *http.Client) *RefreshLorasSdapiV1RefreshLorasPostParams {
	return &RefreshLorasSdapiV1RefreshLorasPostParams{
		HTTPClient: client,
	}
}

/*
RefreshLorasSdapiV1RefreshLorasPostParams contains all the parameters to send to the API endpoint

	for the refresh loras sdapi v1 refresh loras post operation.

	Typically these are written to a http.Request.
*/
type RefreshLorasSdapiV1RefreshLorasPostParams struct {
	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the refresh loras sdapi v1 refresh loras post params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *RefreshLorasSdapiV1RefreshLorasPostParams) WithDefaults() *RefreshLorasSdapiV1RefreshLorasPostParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the refresh loras sdapi v1 refresh loras post params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *RefreshLorasSdapiV1RefreshLorasPostParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the refresh loras sdapi v1 refresh loras post params
func (o *RefreshLorasSdapiV1RefreshLorasPostParams) WithTimeout(timeout time.Duration) *RefreshLorasSdapiV1RefreshLorasPostParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the refresh loras sdapi v1 refresh loras post params
func (o *RefreshLorasSdapiV1RefreshLorasPostParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the refresh loras sdapi v1 refresh loras post params
func (o *RefreshLorasSdapiV1RefreshLorasPostParams) WithContext(ctx context.Context) *RefreshLorasSdapiV1RefreshLorasPostParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the refresh loras sdapi v1 refresh loras post params
func (o *RefreshLorasSdapiV1RefreshLorasPostParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the refresh loras sdapi v1 refresh loras post params
func (o *RefreshLorasSdapiV1RefreshLorasPostParams) WithHTTPClient(client *http.Client) *RefreshLorasSdapiV1RefreshLorasPostParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the refresh loras sdapi v1 refresh loras post params
func (o *RefreshLorasSdapiV1RefreshLorasPostParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WriteToRequest writes these params to a swagger request
func (o *RefreshLorasSdapiV1RefreshLorasPostParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
