// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewRefreshLycosSdapiV1RefreshLycosPostParams creates a new RefreshLycosSdapiV1RefreshLycosPostParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewRefreshLycosSdapiV1RefreshLycosPostParams() *RefreshLycosSdapiV1RefreshLycosPostParams {
	return &RefreshLycosSdapiV1RefreshLycosPostParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewRefreshLycosSdapiV1RefreshLycosPostParamsWithTimeout creates a new RefreshLycosSdapiV1RefreshLycosPostParams object
// with the ability to set a timeout on a request.
func NewRefreshLycosSdapiV1RefreshLycosPostParamsWithTimeout(timeout time.Duration) *RefreshLycosSdapiV1RefreshLycosPostParams {
	return &RefreshLycosSdapiV1RefreshLycosPostParams{
		timeout: timeout,
	}
}

// NewRefreshLycosSdapiV1RefreshLycosPostParamsWithContext creates a new RefreshLycosSdapiV1RefreshLycosPostParams object
// with the ability to set a context for a request.
func NewRefreshLycosSdapiV1RefreshLycosPostParamsWithContext(ctx context.Context) *RefreshLycosSdapiV1RefreshLycosPostParams {
	return &RefreshLycosSdapiV1RefreshLycosPostParams{
		Context: ctx,
	}
}

// NewRefreshLycosSdapiV1RefreshLycosPostParamsWithHTTPClient creates a new RefreshLycosSdapiV1RefreshLycosPostParams object
// with the ability to set a custom HTTPClient for a request.
func NewRefreshLycosSdapiV1RefreshLycosPostParamsWithHTTPClient(client *http.Client) *RefreshLycosSdapiV1RefreshLycosPostParams {
	return &RefreshLycosSdapiV1RefreshLycosPostParams{
		HTTPClient: client,
	}
}

/*
RefreshLycosSdapiV1RefreshLycosPostParams contains all the parameters to send to the API endpoint

	for the refresh lycos sdapi v1 refresh lycos post operation.

	Typically these are written to a http.Request.
*/
type RefreshLycosSdapiV1RefreshLycosPostParams struct {
	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the refresh lycos sdapi v1 refresh lycos post params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *RefreshLycosSdapiV1RefreshLycosPostParams) WithDefaults() *RefreshLycosSdapiV1RefreshLycosPostParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the refresh lycos sdapi v1 refresh lycos post params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *RefreshLycosSdapiV1RefreshLycosPostParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the refresh lycos sdapi v1 refresh lycos post params
func (o *RefreshLycosSdapiV1RefreshLycosPostParams) WithTimeout(timeout time.Duration) *RefreshLycosSdapiV1RefreshLycosPostParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the refresh lycos sdapi v1 refresh lycos post params
func (o *RefreshLycosSdapiV1RefreshLycosPostParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the refresh lycos sdapi v1 refresh lycos post params
func (o *RefreshLycosSdapiV1RefreshLycosPostParams) WithContext(ctx context.Context) *RefreshLycosSdapiV1RefreshLycosPostParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the refresh lycos sdapi v1 refresh lycos post params
func (o *RefreshLycosSdapiV1RefreshLycosPostParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the refresh lycos sdapi v1 refresh lycos post params
func (o *RefreshLycosSdapiV1RefreshLycosPostParams) WithHTTPClient(client *http.Client) *RefreshLycosSdapiV1RefreshLycosPostParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the refresh lycos sdapi v1 refresh lycos post params
func (o *RefreshLycosSdapiV1RefreshLycosPostParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WriteToRequest writes these params to a swagger request
func (o *RefreshLycosSdapiV1RefreshLycosPostParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
