// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/SpenserCai/sd-webui-go/stablediffusion/models"
)

// RemoveCustomTagInfiniteImageBrowsingDbRemoveCustomTagPostReader is a Reader for the RemoveCustomTagInfiniteImageBrowsingDbRemoveCustomTagPost structure.
type RemoveCustomTagInfiniteImageBrowsingDbRemoveCustomTagPostReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *RemoveCustomTagInfiniteImageBrowsingDbRemoveCustomTagPostReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewRemoveCustomTagInfiniteImageBrowsingDbRemoveCustomTagPostOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 422:
		result := NewRemoveCustomTagInfiniteImageBrowsingDbRemoveCustomTagPostUnprocessableEntity()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewRemoveCustomTagInfiniteImageBrowsingDbRemoveCustomTagPostInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewRemoveCustomTagInfiniteImageBrowsingDbRemoveCustomTagPostOK creates a RemoveCustomTagInfiniteImageBrowsingDbRemoveCustomTagPostOK with default headers values
func NewRemoveCustomTagInfiniteImageBrowsingDbRemoveCustomTagPostOK() *RemoveCustomTagInfiniteImageBrowsingDbRemoveCustomTagPostOK {
	return &RemoveCustomTagInfiniteImageBrowsingDbRemoveCustomTagPostOK{}
}

/*
RemoveCustomTagInfiniteImageBrowsingDbRemoveCustomTagPostOK describes a response with status code 200, with default header values.

Successful Response
*/
type RemoveCustomTagInfiniteImageBrowsingDbRemoveCustomTagPostOK struct {
	Payload interface{}
}

// IsSuccess returns true when this remove custom tag infinite image browsing db remove custom tag post o k response has a 2xx status code
func (o *RemoveCustomTagInfiniteImageBrowsingDbRemoveCustomTagPostOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this remove custom tag infinite image browsing db remove custom tag post o k response has a 3xx status code
func (o *RemoveCustomTagInfiniteImageBrowsingDbRemoveCustomTagPostOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this remove custom tag infinite image browsing db remove custom tag post o k response has a 4xx status code
func (o *RemoveCustomTagInfiniteImageBrowsingDbRemoveCustomTagPostOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this remove custom tag infinite image browsing db remove custom tag post o k response has a 5xx status code
func (o *RemoveCustomTagInfiniteImageBrowsingDbRemoveCustomTagPostOK) IsServerError() bool {
	return false
}

// IsCode returns true when this remove custom tag infinite image browsing db remove custom tag post o k response a status code equal to that given
func (o *RemoveCustomTagInfiniteImageBrowsingDbRemoveCustomTagPostOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the remove custom tag infinite image browsing db remove custom tag post o k response
func (o *RemoveCustomTagInfiniteImageBrowsingDbRemoveCustomTagPostOK) Code() int {
	return 200
}

func (o *RemoveCustomTagInfiniteImageBrowsingDbRemoveCustomTagPostOK) Error() string {
	return fmt.Sprintf("[POST /infinite_image_browsing/db/remove_custom_tag][%d] removeCustomTagInfiniteImageBrowsingDbRemoveCustomTagPostOK  %+v", 200, o.Payload)
}

func (o *RemoveCustomTagInfiniteImageBrowsingDbRemoveCustomTagPostOK) String() string {
	return fmt.Sprintf("[POST /infinite_image_browsing/db/remove_custom_tag][%d] removeCustomTagInfiniteImageBrowsingDbRemoveCustomTagPostOK  %+v", 200, o.Payload)
}

func (o *RemoveCustomTagInfiniteImageBrowsingDbRemoveCustomTagPostOK) GetPayload() interface{} {
	return o.Payload
}

func (o *RemoveCustomTagInfiniteImageBrowsingDbRemoveCustomTagPostOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewRemoveCustomTagInfiniteImageBrowsingDbRemoveCustomTagPostUnprocessableEntity creates a RemoveCustomTagInfiniteImageBrowsingDbRemoveCustomTagPostUnprocessableEntity with default headers values
func NewRemoveCustomTagInfiniteImageBrowsingDbRemoveCustomTagPostUnprocessableEntity() *RemoveCustomTagInfiniteImageBrowsingDbRemoveCustomTagPostUnprocessableEntity {
	return &RemoveCustomTagInfiniteImageBrowsingDbRemoveCustomTagPostUnprocessableEntity{}
}

/*
RemoveCustomTagInfiniteImageBrowsingDbRemoveCustomTagPostUnprocessableEntity describes a response with status code 422, with default header values.

Validation Error
*/
type RemoveCustomTagInfiniteImageBrowsingDbRemoveCustomTagPostUnprocessableEntity struct {
	Payload *models.HTTPValidationError
}

// IsSuccess returns true when this remove custom tag infinite image browsing db remove custom tag post unprocessable entity response has a 2xx status code
func (o *RemoveCustomTagInfiniteImageBrowsingDbRemoveCustomTagPostUnprocessableEntity) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this remove custom tag infinite image browsing db remove custom tag post unprocessable entity response has a 3xx status code
func (o *RemoveCustomTagInfiniteImageBrowsingDbRemoveCustomTagPostUnprocessableEntity) IsRedirect() bool {
	return false
}

// IsClientError returns true when this remove custom tag infinite image browsing db remove custom tag post unprocessable entity response has a 4xx status code
func (o *RemoveCustomTagInfiniteImageBrowsingDbRemoveCustomTagPostUnprocessableEntity) IsClientError() bool {
	return true
}

// IsServerError returns true when this remove custom tag infinite image browsing db remove custom tag post unprocessable entity response has a 5xx status code
func (o *RemoveCustomTagInfiniteImageBrowsingDbRemoveCustomTagPostUnprocessableEntity) IsServerError() bool {
	return false
}

// IsCode returns true when this remove custom tag infinite image browsing db remove custom tag post unprocessable entity response a status code equal to that given
func (o *RemoveCustomTagInfiniteImageBrowsingDbRemoveCustomTagPostUnprocessableEntity) IsCode(code int) bool {
	return code == 422
}

// Code gets the status code for the remove custom tag infinite image browsing db remove custom tag post unprocessable entity response
func (o *RemoveCustomTagInfiniteImageBrowsingDbRemoveCustomTagPostUnprocessableEntity) Code() int {
	return 422
}

func (o *RemoveCustomTagInfiniteImageBrowsingDbRemoveCustomTagPostUnprocessableEntity) Error() string {
	return fmt.Sprintf("[POST /infinite_image_browsing/db/remove_custom_tag][%d] removeCustomTagInfiniteImageBrowsingDbRemoveCustomTagPostUnprocessableEntity  %+v", 422, o.Payload)
}

func (o *RemoveCustomTagInfiniteImageBrowsingDbRemoveCustomTagPostUnprocessableEntity) String() string {
	return fmt.Sprintf("[POST /infinite_image_browsing/db/remove_custom_tag][%d] removeCustomTagInfiniteImageBrowsingDbRemoveCustomTagPostUnprocessableEntity  %+v", 422, o.Payload)
}

func (o *RemoveCustomTagInfiniteImageBrowsingDbRemoveCustomTagPostUnprocessableEntity) GetPayload() *models.HTTPValidationError {
	return o.Payload
}

func (o *RemoveCustomTagInfiniteImageBrowsingDbRemoveCustomTagPostUnprocessableEntity) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.HTTPValidationError)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewRemoveCustomTagInfiniteImageBrowsingDbRemoveCustomTagPostInternalServerError creates a RemoveCustomTagInfiniteImageBrowsingDbRemoveCustomTagPostInternalServerError with default headers values
func NewRemoveCustomTagInfiniteImageBrowsingDbRemoveCustomTagPostInternalServerError() *RemoveCustomTagInfiniteImageBrowsingDbRemoveCustomTagPostInternalServerError {
	return &RemoveCustomTagInfiniteImageBrowsingDbRemoveCustomTagPostInternalServerError{}
}

/*
RemoveCustomTagInfiniteImageBrowsingDbRemoveCustomTagPostInternalServerError describes a response with status code 500, with default header values.

HTTPException
*/
type RemoveCustomTagInfiniteImageBrowsingDbRemoveCustomTagPostInternalServerError struct {
	Payload *models.HTTPException
}

// IsSuccess returns true when this remove custom tag infinite image browsing db remove custom tag post internal server error response has a 2xx status code
func (o *RemoveCustomTagInfiniteImageBrowsingDbRemoveCustomTagPostInternalServerError) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this remove custom tag infinite image browsing db remove custom tag post internal server error response has a 3xx status code
func (o *RemoveCustomTagInfiniteImageBrowsingDbRemoveCustomTagPostInternalServerError) IsRedirect() bool {
	return false
}

// IsClientError returns true when this remove custom tag infinite image browsing db remove custom tag post internal server error response has a 4xx status code
func (o *RemoveCustomTagInfiniteImageBrowsingDbRemoveCustomTagPostInternalServerError) IsClientError() bool {
	return false
}

// IsServerError returns true when this remove custom tag infinite image browsing db remove custom tag post internal server error response has a 5xx status code
func (o *RemoveCustomTagInfiniteImageBrowsingDbRemoveCustomTagPostInternalServerError) IsServerError() bool {
	return true
}

// IsCode returns true when this remove custom tag infinite image browsing db remove custom tag post internal server error response a status code equal to that given
func (o *RemoveCustomTagInfiniteImageBrowsingDbRemoveCustomTagPostInternalServerError) IsCode(code int) bool {
	return code == 500
}

// Code gets the status code for the remove custom tag infinite image browsing db remove custom tag post internal server error response
func (o *RemoveCustomTagInfiniteImageBrowsingDbRemoveCustomTagPostInternalServerError) Code() int {
	return 500
}

func (o *RemoveCustomTagInfiniteImageBrowsingDbRemoveCustomTagPostInternalServerError) Error() string {
	return fmt.Sprintf("[POST /infinite_image_browsing/db/remove_custom_tag][%d] removeCustomTagInfiniteImageBrowsingDbRemoveCustomTagPostInternalServerError  %+v", 500, o.Payload)
}

func (o *RemoveCustomTagInfiniteImageBrowsingDbRemoveCustomTagPostInternalServerError) String() string {
	return fmt.Sprintf("[POST /infinite_image_browsing/db/remove_custom_tag][%d] removeCustomTagInfiniteImageBrowsingDbRemoveCustomTagPostInternalServerError  %+v", 500, o.Payload)
}

func (o *RemoveCustomTagInfiniteImageBrowsingDbRemoveCustomTagPostInternalServerError) GetPayload() *models.HTTPException {
	return o.Payload
}

func (o *RemoveCustomTagInfiniteImageBrowsingDbRemoveCustomTagPostInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.HTTPException)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
