// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/SpenserCai/sd-webui-go/stablediffusion/models"
)

// RoopImageRoopImagePostReader is a Reader for the RoopImageRoopImagePost structure.
type RoopImageRoopImagePostReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *RoopImageRoopImagePostReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewRoopImageRoopImagePostOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 422:
		result := NewRoopImageRoopImagePostUnprocessableEntity()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewRoopImageRoopImagePostInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewRoopImageRoopImagePostOK creates a RoopImageRoopImagePostOK with default headers values
func NewRoopImageRoopImagePostOK() *RoopImageRoopImagePostOK {
	return &RoopImageRoopImagePostOK{}
}

/*
RoopImageRoopImagePostOK describes a response with status code 200, with default header values.

Successful Response
*/
type RoopImageRoopImagePostOK struct {
	Payload interface{}
}

// IsSuccess returns true when this roop image roop image post o k response has a 2xx status code
func (o *RoopImageRoopImagePostOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this roop image roop image post o k response has a 3xx status code
func (o *RoopImageRoopImagePostOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this roop image roop image post o k response has a 4xx status code
func (o *RoopImageRoopImagePostOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this roop image roop image post o k response has a 5xx status code
func (o *RoopImageRoopImagePostOK) IsServerError() bool {
	return false
}

// IsCode returns true when this roop image roop image post o k response a status code equal to that given
func (o *RoopImageRoopImagePostOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the roop image roop image post o k response
func (o *RoopImageRoopImagePostOK) Code() int {
	return 200
}

func (o *RoopImageRoopImagePostOK) Error() string {
	return fmt.Sprintf("[POST /roop/image][%d] roopImageRoopImagePostOK  %+v", 200, o.Payload)
}

func (o *RoopImageRoopImagePostOK) String() string {
	return fmt.Sprintf("[POST /roop/image][%d] roopImageRoopImagePostOK  %+v", 200, o.Payload)
}

func (o *RoopImageRoopImagePostOK) GetPayload() interface{} {
	return o.Payload
}

func (o *RoopImageRoopImagePostOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewRoopImageRoopImagePostUnprocessableEntity creates a RoopImageRoopImagePostUnprocessableEntity with default headers values
func NewRoopImageRoopImagePostUnprocessableEntity() *RoopImageRoopImagePostUnprocessableEntity {
	return &RoopImageRoopImagePostUnprocessableEntity{}
}

/*
RoopImageRoopImagePostUnprocessableEntity describes a response with status code 422, with default header values.

Validation Error
*/
type RoopImageRoopImagePostUnprocessableEntity struct {
	Payload *models.HTTPValidationError
}

// IsSuccess returns true when this roop image roop image post unprocessable entity response has a 2xx status code
func (o *RoopImageRoopImagePostUnprocessableEntity) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this roop image roop image post unprocessable entity response has a 3xx status code
func (o *RoopImageRoopImagePostUnprocessableEntity) IsRedirect() bool {
	return false
}

// IsClientError returns true when this roop image roop image post unprocessable entity response has a 4xx status code
func (o *RoopImageRoopImagePostUnprocessableEntity) IsClientError() bool {
	return true
}

// IsServerError returns true when this roop image roop image post unprocessable entity response has a 5xx status code
func (o *RoopImageRoopImagePostUnprocessableEntity) IsServerError() bool {
	return false
}

// IsCode returns true when this roop image roop image post unprocessable entity response a status code equal to that given
func (o *RoopImageRoopImagePostUnprocessableEntity) IsCode(code int) bool {
	return code == 422
}

// Code gets the status code for the roop image roop image post unprocessable entity response
func (o *RoopImageRoopImagePostUnprocessableEntity) Code() int {
	return 422
}

func (o *RoopImageRoopImagePostUnprocessableEntity) Error() string {
	return fmt.Sprintf("[POST /roop/image][%d] roopImageRoopImagePostUnprocessableEntity  %+v", 422, o.Payload)
}

func (o *RoopImageRoopImagePostUnprocessableEntity) String() string {
	return fmt.Sprintf("[POST /roop/image][%d] roopImageRoopImagePostUnprocessableEntity  %+v", 422, o.Payload)
}

func (o *RoopImageRoopImagePostUnprocessableEntity) GetPayload() *models.HTTPValidationError {
	return o.Payload
}

func (o *RoopImageRoopImagePostUnprocessableEntity) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.HTTPValidationError)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewRoopImageRoopImagePostInternalServerError creates a RoopImageRoopImagePostInternalServerError with default headers values
func NewRoopImageRoopImagePostInternalServerError() *RoopImageRoopImagePostInternalServerError {
	return &RoopImageRoopImagePostInternalServerError{}
}

/*
RoopImageRoopImagePostInternalServerError describes a response with status code 500, with default header values.

HTTPException
*/
type RoopImageRoopImagePostInternalServerError struct {
	Payload *models.HTTPException
}

// IsSuccess returns true when this roop image roop image post internal server error response has a 2xx status code
func (o *RoopImageRoopImagePostInternalServerError) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this roop image roop image post internal server error response has a 3xx status code
func (o *RoopImageRoopImagePostInternalServerError) IsRedirect() bool {
	return false
}

// IsClientError returns true when this roop image roop image post internal server error response has a 4xx status code
func (o *RoopImageRoopImagePostInternalServerError) IsClientError() bool {
	return false
}

// IsServerError returns true when this roop image roop image post internal server error response has a 5xx status code
func (o *RoopImageRoopImagePostInternalServerError) IsServerError() bool {
	return true
}

// IsCode returns true when this roop image roop image post internal server error response a status code equal to that given
func (o *RoopImageRoopImagePostInternalServerError) IsCode(code int) bool {
	return code == 500
}

// Code gets the status code for the roop image roop image post internal server error response
func (o *RoopImageRoopImagePostInternalServerError) Code() int {
	return 500
}

func (o *RoopImageRoopImagePostInternalServerError) Error() string {
	return fmt.Sprintf("[POST /roop/image][%d] roopImageRoopImagePostInternalServerError  %+v", 500, o.Payload)
}

func (o *RoopImageRoopImagePostInternalServerError) String() string {
	return fmt.Sprintf("[POST /roop/image][%d] roopImageRoopImagePostInternalServerError  %+v", 500, o.Payload)
}

func (o *RoopImageRoopImagePostInternalServerError) GetPayload() *models.HTTPException {
	return o.Payload
}

func (o *RoopImageRoopImagePostInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.HTTPException)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
