// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"github.com/SpenserCai/sd-webui-go/stablediffusion/models"
)

// NewRoopImageRoopImagePostParams creates a new RoopImageRoopImagePostParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewRoopImageRoopImagePostParams() *RoopImageRoopImagePostParams {
	return &RoopImageRoopImagePostParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewRoopImageRoopImagePostParamsWithTimeout creates a new RoopImageRoopImagePostParams object
// with the ability to set a timeout on a request.
func NewRoopImageRoopImagePostParamsWithTimeout(timeout time.Duration) *RoopImageRoopImagePostParams {
	return &RoopImageRoopImagePostParams{
		timeout: timeout,
	}
}

// NewRoopImageRoopImagePostParamsWithContext creates a new RoopImageRoopImagePostParams object
// with the ability to set a context for a request.
func NewRoopImageRoopImagePostParamsWithContext(ctx context.Context) *RoopImageRoopImagePostParams {
	return &RoopImageRoopImagePostParams{
		Context: ctx,
	}
}

// NewRoopImageRoopImagePostParamsWithHTTPClient creates a new RoopImageRoopImagePostParams object
// with the ability to set a custom HTTPClient for a request.
func NewRoopImageRoopImagePostParamsWithHTTPClient(client *http.Client) *RoopImageRoopImagePostParams {
	return &RoopImageRoopImagePostParams{
		HTTPClient: client,
	}
}

/*
RoopImageRoopImagePostParams contains all the parameters to send to the API endpoint

	for the roop image roop image post operation.

	Typically these are written to a http.Request.
*/
type RoopImageRoopImagePostParams struct {

	// Body.
	Body *models.BodyRoopImageRoopImagePost

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the roop image roop image post params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *RoopImageRoopImagePostParams) WithDefaults() *RoopImageRoopImagePostParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the roop image roop image post params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *RoopImageRoopImagePostParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the roop image roop image post params
func (o *RoopImageRoopImagePostParams) WithTimeout(timeout time.Duration) *RoopImageRoopImagePostParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the roop image roop image post params
func (o *RoopImageRoopImagePostParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the roop image roop image post params
func (o *RoopImageRoopImagePostParams) WithContext(ctx context.Context) *RoopImageRoopImagePostParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the roop image roop image post params
func (o *RoopImageRoopImagePostParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the roop image roop image post params
func (o *RoopImageRoopImagePostParams) WithHTTPClient(client *http.Client) *RoopImageRoopImagePostParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the roop image roop image post params
func (o *RoopImageRoopImagePostParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the roop image roop image post params
func (o *RoopImageRoopImagePostParams) WithBody(body *models.BodyRoopImageRoopImagePost) *RoopImageRoopImagePostParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the roop image roop image post params
func (o *RoopImageRoopImagePostParams) SetBody(body *models.BodyRoopImageRoopImagePost) {
	o.Body = body
}

// WriteToRequest writes these params to a swagger request
func (o *RoopImageRoopImagePostParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error
	if o.Body != nil {
		if err := r.SetBodyParam(o.Body); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
