// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// T2vVersionT2vVersionGetReader is a Reader for the T2vVersionT2vVersionGet structure.
type T2vVersionT2vVersionGetReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *T2vVersionT2vVersionGetReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewT2vVersionT2vVersionGetOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewT2vVersionT2vVersionGetOK creates a T2vVersionT2vVersionGetOK with default headers values
func NewT2vVersionT2vVersionGetOK() *T2vVersionT2vVersionGetOK {
	return &T2vVersionT2vVersionGetOK{}
}

/*
T2vVersionT2vVersionGetOK describes a response with status code 200, with default header values.

Successful Response
*/
type T2vVersionT2vVersionGetOK struct {
	Payload interface{}
}

// IsSuccess returns true when this t2v version t2v version get o k response has a 2xx status code
func (o *T2vVersionT2vVersionGetOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this t2v version t2v version get o k response has a 3xx status code
func (o *T2vVersionT2vVersionGetOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this t2v version t2v version get o k response has a 4xx status code
func (o *T2vVersionT2vVersionGetOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this t2v version t2v version get o k response has a 5xx status code
func (o *T2vVersionT2vVersionGetOK) IsServerError() bool {
	return false
}

// IsCode returns true when this t2v version t2v version get o k response a status code equal to that given
func (o *T2vVersionT2vVersionGetOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the t2v version t2v version get o k response
func (o *T2vVersionT2vVersionGetOK) Code() int {
	return 200
}

func (o *T2vVersionT2vVersionGetOK) Error() string {
	return fmt.Sprintf("[GET /t2v/version][%d] t2vVersionT2vVersionGetOK  %+v", 200, o.Payload)
}

func (o *T2vVersionT2vVersionGetOK) String() string {
	return fmt.Sprintf("[GET /t2v/version][%d] t2vVersionT2vVersionGetOK  %+v", 200, o.Payload)
}

func (o *T2vVersionT2vVersionGetOK) GetPayload() interface{} {
	return o.Payload
}

func (o *T2vVersionT2vVersionGetOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
