// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewT2vVersionT2vVersionGetParams creates a new T2vVersionT2vVersionGetParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewT2vVersionT2vVersionGetParams() *T2vVersionT2vVersionGetParams {
	return &T2vVersionT2vVersionGetParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewT2vVersionT2vVersionGetParamsWithTimeout creates a new T2vVersionT2vVersionGetParams object
// with the ability to set a timeout on a request.
func NewT2vVersionT2vVersionGetParamsWithTimeout(timeout time.Duration) *T2vVersionT2vVersionGetParams {
	return &T2vVersionT2vVersionGetParams{
		timeout: timeout,
	}
}

// NewT2vVersionT2vVersionGetParamsWithContext creates a new T2vVersionT2vVersionGetParams object
// with the ability to set a context for a request.
func NewT2vVersionT2vVersionGetParamsWithContext(ctx context.Context) *T2vVersionT2vVersionGetParams {
	return &T2vVersionT2vVersionGetParams{
		Context: ctx,
	}
}

// NewT2vVersionT2vVersionGetParamsWithHTTPClient creates a new T2vVersionT2vVersionGetParams object
// with the ability to set a custom HTTPClient for a request.
func NewT2vVersionT2vVersionGetParamsWithHTTPClient(client *http.Client) *T2vVersionT2vVersionGetParams {
	return &T2vVersionT2vVersionGetParams{
		HTTPClient: client,
	}
}

/*
T2vVersionT2vVersionGetParams contains all the parameters to send to the API endpoint

	for the t2v version t2v version get operation.

	Typically these are written to a http.Request.
*/
type T2vVersionT2vVersionGetParams struct {
	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the t2v version t2v version get params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *T2vVersionT2vVersionGetParams) WithDefaults() *T2vVersionT2vVersionGetParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the t2v version t2v version get params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *T2vVersionT2vVersionGetParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the t2v version t2v version get params
func (o *T2vVersionT2vVersionGetParams) WithTimeout(timeout time.Duration) *T2vVersionT2vVersionGetParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the t2v version t2v version get params
func (o *T2vVersionT2vVersionGetParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the t2v version t2v version get params
func (o *T2vVersionT2vVersionGetParams) WithContext(ctx context.Context) *T2vVersionT2vVersionGetParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the t2v version t2v version get params
func (o *T2vVersionT2vVersionGetParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the t2v version t2v version get params
func (o *T2vVersionT2vVersionGetParams) WithHTTPClient(client *http.Client) *T2vVersionT2vVersionGetParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the t2v version t2v version get params
func (o *T2vVersionT2vVersionGetParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WriteToRequest writes these params to a swagger request
func (o *T2vVersionT2vVersionGetParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
