// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/SpenserCai/sd-webui-go/stablediffusion/models"
)

// Text2imgapiSdapiV1Txt2imgPostReader is a Reader for the Text2imgapiSdapiV1Txt2imgPost structure.
type Text2imgapiSdapiV1Txt2imgPostReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *Text2imgapiSdapiV1Txt2imgPostReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewText2imgapiSdapiV1Txt2imgPostOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 422:
		result := NewText2imgapiSdapiV1Txt2imgPostUnprocessableEntity()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewText2imgapiSdapiV1Txt2imgPostOK creates a Text2imgapiSdapiV1Txt2imgPostOK with default headers values
func NewText2imgapiSdapiV1Txt2imgPostOK() *Text2imgapiSdapiV1Txt2imgPostOK {
	return &Text2imgapiSdapiV1Txt2imgPostOK{}
}

/*
Text2imgapiSdapiV1Txt2imgPostOK describes a response with status code 200, with default header values.

Successful Response
*/
type Text2imgapiSdapiV1Txt2imgPostOK struct {
	Payload *models.TextToImageResponse
}

// IsSuccess returns true when this text2imgapi sdapi v1 txt2img post o k response has a 2xx status code
func (o *Text2imgapiSdapiV1Txt2imgPostOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this text2imgapi sdapi v1 txt2img post o k response has a 3xx status code
func (o *Text2imgapiSdapiV1Txt2imgPostOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this text2imgapi sdapi v1 txt2img post o k response has a 4xx status code
func (o *Text2imgapiSdapiV1Txt2imgPostOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this text2imgapi sdapi v1 txt2img post o k response has a 5xx status code
func (o *Text2imgapiSdapiV1Txt2imgPostOK) IsServerError() bool {
	return false
}

// IsCode returns true when this text2imgapi sdapi v1 txt2img post o k response a status code equal to that given
func (o *Text2imgapiSdapiV1Txt2imgPostOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the text2imgapi sdapi v1 txt2img post o k response
func (o *Text2imgapiSdapiV1Txt2imgPostOK) Code() int {
	return 200
}

func (o *Text2imgapiSdapiV1Txt2imgPostOK) Error() string {
	return fmt.Sprintf("[POST /sdapi/v1/txt2img][%d] text2imgapiSdapiV1Txt2imgPostOK  %+v", 200, o.Payload)
}

func (o *Text2imgapiSdapiV1Txt2imgPostOK) String() string {
	return fmt.Sprintf("[POST /sdapi/v1/txt2img][%d] text2imgapiSdapiV1Txt2imgPostOK  %+v", 200, o.Payload)
}

func (o *Text2imgapiSdapiV1Txt2imgPostOK) GetPayload() *models.TextToImageResponse {
	return o.Payload
}

func (o *Text2imgapiSdapiV1Txt2imgPostOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.TextToImageResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewText2imgapiSdapiV1Txt2imgPostUnprocessableEntity creates a Text2imgapiSdapiV1Txt2imgPostUnprocessableEntity with default headers values
func NewText2imgapiSdapiV1Txt2imgPostUnprocessableEntity() *Text2imgapiSdapiV1Txt2imgPostUnprocessableEntity {
	return &Text2imgapiSdapiV1Txt2imgPostUnprocessableEntity{}
}

/*
Text2imgapiSdapiV1Txt2imgPostUnprocessableEntity describes a response with status code 422, with default header values.

Validation Error
*/
type Text2imgapiSdapiV1Txt2imgPostUnprocessableEntity struct {
	Payload *models.HTTPValidationError
}

// IsSuccess returns true when this text2imgapi sdapi v1 txt2img post unprocessable entity response has a 2xx status code
func (o *Text2imgapiSdapiV1Txt2imgPostUnprocessableEntity) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this text2imgapi sdapi v1 txt2img post unprocessable entity response has a 3xx status code
func (o *Text2imgapiSdapiV1Txt2imgPostUnprocessableEntity) IsRedirect() bool {
	return false
}

// IsClientError returns true when this text2imgapi sdapi v1 txt2img post unprocessable entity response has a 4xx status code
func (o *Text2imgapiSdapiV1Txt2imgPostUnprocessableEntity) IsClientError() bool {
	return true
}

// IsServerError returns true when this text2imgapi sdapi v1 txt2img post unprocessable entity response has a 5xx status code
func (o *Text2imgapiSdapiV1Txt2imgPostUnprocessableEntity) IsServerError() bool {
	return false
}

// IsCode returns true when this text2imgapi sdapi v1 txt2img post unprocessable entity response a status code equal to that given
func (o *Text2imgapiSdapiV1Txt2imgPostUnprocessableEntity) IsCode(code int) bool {
	return code == 422
}

// Code gets the status code for the text2imgapi sdapi v1 txt2img post unprocessable entity response
func (o *Text2imgapiSdapiV1Txt2imgPostUnprocessableEntity) Code() int {
	return 422
}

func (o *Text2imgapiSdapiV1Txt2imgPostUnprocessableEntity) Error() string {
	return fmt.Sprintf("[POST /sdapi/v1/txt2img][%d] text2imgapiSdapiV1Txt2imgPostUnprocessableEntity  %+v", 422, o.Payload)
}

func (o *Text2imgapiSdapiV1Txt2imgPostUnprocessableEntity) String() string {
	return fmt.Sprintf("[POST /sdapi/v1/txt2img][%d] text2imgapiSdapiV1Txt2imgPostUnprocessableEntity  %+v", 422, o.Payload)
}

func (o *Text2imgapiSdapiV1Txt2imgPostUnprocessableEntity) GetPayload() *models.HTTPValidationError {
	return o.Payload
}

func (o *Text2imgapiSdapiV1Txt2imgPostUnprocessableEntity) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.HTTPValidationError)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
