// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewThemeCSSThemeCSSGetParams creates a new ThemeCSSThemeCSSGetParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewThemeCSSThemeCSSGetParams() *ThemeCSSThemeCSSGetParams {
	return &ThemeCSSThemeCSSGetParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewThemeCSSThemeCSSGetParamsWithTimeout creates a new ThemeCSSThemeCSSGetParams object
// with the ability to set a timeout on a request.
func NewThemeCSSThemeCSSGetParamsWithTimeout(timeout time.Duration) *ThemeCSSThemeCSSGetParams {
	return &ThemeCSSThemeCSSGetParams{
		timeout: timeout,
	}
}

// NewThemeCSSThemeCSSGetParamsWithContext creates a new ThemeCSSThemeCSSGetParams object
// with the ability to set a context for a request.
func NewThemeCSSThemeCSSGetParamsWithContext(ctx context.Context) *ThemeCSSThemeCSSGetParams {
	return &ThemeCSSThemeCSSGetParams{
		Context: ctx,
	}
}

// NewThemeCSSThemeCSSGetParamsWithHTTPClient creates a new ThemeCSSThemeCSSGetParams object
// with the ability to set a custom HTTPClient for a request.
func NewThemeCSSThemeCSSGetParamsWithHTTPClient(client *http.Client) *ThemeCSSThemeCSSGetParams {
	return &ThemeCSSThemeCSSGetParams{
		HTTPClient: client,
	}
}

/*
ThemeCSSThemeCSSGetParams contains all the parameters to send to the API endpoint

	for the theme css theme css get operation.

	Typically these are written to a http.Request.
*/
type ThemeCSSThemeCSSGetParams struct {
	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the theme css theme css get params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *ThemeCSSThemeCSSGetParams) WithDefaults() *ThemeCSSThemeCSSGetParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the theme css theme css get params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *ThemeCSSThemeCSSGetParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the theme css theme css get params
func (o *ThemeCSSThemeCSSGetParams) WithTimeout(timeout time.Duration) *ThemeCSSThemeCSSGetParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the theme css theme css get params
func (o *ThemeCSSThemeCSSGetParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the theme css theme css get params
func (o *ThemeCSSThemeCSSGetParams) WithContext(ctx context.Context) *ThemeCSSThemeCSSGetParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the theme css theme css get params
func (o *ThemeCSSThemeCSSGetParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the theme css theme css get params
func (o *ThemeCSSThemeCSSGetParams) WithHTTPClient(client *http.Client) *ThemeCSSThemeCSSGetParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the theme css theme css get params
func (o *ThemeCSSThemeCSSGetParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WriteToRequest writes these params to a swagger request
func (o *ThemeCSSThemeCSSGetParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
