// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/SpenserCai/sd-webui-go/stablediffusion/models"
)

// ToggleCustomTagToImgInfiniteImageBrowsingDbToggleCustomTagToImgPostReader is a Reader for the ToggleCustomTagToImgInfiniteImageBrowsingDbToggleCustomTagToImgPost structure.
type ToggleCustomTagToImgInfiniteImageBrowsingDbToggleCustomTagToImgPostReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *ToggleCustomTagToImgInfiniteImageBrowsingDbToggleCustomTagToImgPostReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewToggleCustomTagToImgInfiniteImageBrowsingDbToggleCustomTagToImgPostOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 422:
		result := NewToggleCustomTagToImgInfiniteImageBrowsingDbToggleCustomTagToImgPostUnprocessableEntity()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewToggleCustomTagToImgInfiniteImageBrowsingDbToggleCustomTagToImgPostOK creates a ToggleCustomTagToImgInfiniteImageBrowsingDbToggleCustomTagToImgPostOK with default headers values
func NewToggleCustomTagToImgInfiniteImageBrowsingDbToggleCustomTagToImgPostOK() *ToggleCustomTagToImgInfiniteImageBrowsingDbToggleCustomTagToImgPostOK {
	return &ToggleCustomTagToImgInfiniteImageBrowsingDbToggleCustomTagToImgPostOK{}
}

/*
ToggleCustomTagToImgInfiniteImageBrowsingDbToggleCustomTagToImgPostOK describes a response with status code 200, with default header values.

Successful Response
*/
type ToggleCustomTagToImgInfiniteImageBrowsingDbToggleCustomTagToImgPostOK struct {
	Payload interface{}
}

// IsSuccess returns true when this toggle custom tag to img infinite image browsing db toggle custom tag to img post o k response has a 2xx status code
func (o *ToggleCustomTagToImgInfiniteImageBrowsingDbToggleCustomTagToImgPostOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this toggle custom tag to img infinite image browsing db toggle custom tag to img post o k response has a 3xx status code
func (o *ToggleCustomTagToImgInfiniteImageBrowsingDbToggleCustomTagToImgPostOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this toggle custom tag to img infinite image browsing db toggle custom tag to img post o k response has a 4xx status code
func (o *ToggleCustomTagToImgInfiniteImageBrowsingDbToggleCustomTagToImgPostOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this toggle custom tag to img infinite image browsing db toggle custom tag to img post o k response has a 5xx status code
func (o *ToggleCustomTagToImgInfiniteImageBrowsingDbToggleCustomTagToImgPostOK) IsServerError() bool {
	return false
}

// IsCode returns true when this toggle custom tag to img infinite image browsing db toggle custom tag to img post o k response a status code equal to that given
func (o *ToggleCustomTagToImgInfiniteImageBrowsingDbToggleCustomTagToImgPostOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the toggle custom tag to img infinite image browsing db toggle custom tag to img post o k response
func (o *ToggleCustomTagToImgInfiniteImageBrowsingDbToggleCustomTagToImgPostOK) Code() int {
	return 200
}

func (o *ToggleCustomTagToImgInfiniteImageBrowsingDbToggleCustomTagToImgPostOK) Error() string {
	return fmt.Sprintf("[POST /infinite_image_browsing/db/toggle_custom_tag_to_img][%d] toggleCustomTagToImgInfiniteImageBrowsingDbToggleCustomTagToImgPostOK  %+v", 200, o.Payload)
}

func (o *ToggleCustomTagToImgInfiniteImageBrowsingDbToggleCustomTagToImgPostOK) String() string {
	return fmt.Sprintf("[POST /infinite_image_browsing/db/toggle_custom_tag_to_img][%d] toggleCustomTagToImgInfiniteImageBrowsingDbToggleCustomTagToImgPostOK  %+v", 200, o.Payload)
}

func (o *ToggleCustomTagToImgInfiniteImageBrowsingDbToggleCustomTagToImgPostOK) GetPayload() interface{} {
	return o.Payload
}

func (o *ToggleCustomTagToImgInfiniteImageBrowsingDbToggleCustomTagToImgPostOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewToggleCustomTagToImgInfiniteImageBrowsingDbToggleCustomTagToImgPostUnprocessableEntity creates a ToggleCustomTagToImgInfiniteImageBrowsingDbToggleCustomTagToImgPostUnprocessableEntity with default headers values
func NewToggleCustomTagToImgInfiniteImageBrowsingDbToggleCustomTagToImgPostUnprocessableEntity() *ToggleCustomTagToImgInfiniteImageBrowsingDbToggleCustomTagToImgPostUnprocessableEntity {
	return &ToggleCustomTagToImgInfiniteImageBrowsingDbToggleCustomTagToImgPostUnprocessableEntity{}
}

/*
ToggleCustomTagToImgInfiniteImageBrowsingDbToggleCustomTagToImgPostUnprocessableEntity describes a response with status code 422, with default header values.

Validation Error
*/
type ToggleCustomTagToImgInfiniteImageBrowsingDbToggleCustomTagToImgPostUnprocessableEntity struct {
	Payload *models.HTTPValidationError
}

// IsSuccess returns true when this toggle custom tag to img infinite image browsing db toggle custom tag to img post unprocessable entity response has a 2xx status code
func (o *ToggleCustomTagToImgInfiniteImageBrowsingDbToggleCustomTagToImgPostUnprocessableEntity) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this toggle custom tag to img infinite image browsing db toggle custom tag to img post unprocessable entity response has a 3xx status code
func (o *ToggleCustomTagToImgInfiniteImageBrowsingDbToggleCustomTagToImgPostUnprocessableEntity) IsRedirect() bool {
	return false
}

// IsClientError returns true when this toggle custom tag to img infinite image browsing db toggle custom tag to img post unprocessable entity response has a 4xx status code
func (o *ToggleCustomTagToImgInfiniteImageBrowsingDbToggleCustomTagToImgPostUnprocessableEntity) IsClientError() bool {
	return true
}

// IsServerError returns true when this toggle custom tag to img infinite image browsing db toggle custom tag to img post unprocessable entity response has a 5xx status code
func (o *ToggleCustomTagToImgInfiniteImageBrowsingDbToggleCustomTagToImgPostUnprocessableEntity) IsServerError() bool {
	return false
}

// IsCode returns true when this toggle custom tag to img infinite image browsing db toggle custom tag to img post unprocessable entity response a status code equal to that given
func (o *ToggleCustomTagToImgInfiniteImageBrowsingDbToggleCustomTagToImgPostUnprocessableEntity) IsCode(code int) bool {
	return code == 422
}

// Code gets the status code for the toggle custom tag to img infinite image browsing db toggle custom tag to img post unprocessable entity response
func (o *ToggleCustomTagToImgInfiniteImageBrowsingDbToggleCustomTagToImgPostUnprocessableEntity) Code() int {
	return 422
}

func (o *ToggleCustomTagToImgInfiniteImageBrowsingDbToggleCustomTagToImgPostUnprocessableEntity) Error() string {
	return fmt.Sprintf("[POST /infinite_image_browsing/db/toggle_custom_tag_to_img][%d] toggleCustomTagToImgInfiniteImageBrowsingDbToggleCustomTagToImgPostUnprocessableEntity  %+v", 422, o.Payload)
}

func (o *ToggleCustomTagToImgInfiniteImageBrowsingDbToggleCustomTagToImgPostUnprocessableEntity) String() string {
	return fmt.Sprintf("[POST /infinite_image_browsing/db/toggle_custom_tag_to_img][%d] toggleCustomTagToImgInfiniteImageBrowsingDbToggleCustomTagToImgPostUnprocessableEntity  %+v", 422, o.Payload)
}

func (o *ToggleCustomTagToImgInfiniteImageBrowsingDbToggleCustomTagToImgPostUnprocessableEntity) GetPayload() *models.HTTPValidationError {
	return o.Payload
}

func (o *ToggleCustomTagToImgInfiniteImageBrowsingDbToggleCustomTagToImgPostUnprocessableEntity) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.HTTPValidationError)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
