// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/SpenserCai/sd-webui-go/stablediffusion/models"
)

// TrainHypernetworkSdapiV1TrainHypernetworkPostReader is a Reader for the TrainHypernetworkSdapiV1TrainHypernetworkPost structure.
type TrainHypernetworkSdapiV1TrainHypernetworkPostReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *TrainHypernetworkSdapiV1TrainHypernetworkPostReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewTrainHypernetworkSdapiV1TrainHypernetworkPostOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 422:
		result := NewTrainHypernetworkSdapiV1TrainHypernetworkPostUnprocessableEntity()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewTrainHypernetworkSdapiV1TrainHypernetworkPostOK creates a TrainHypernetworkSdapiV1TrainHypernetworkPostOK with default headers values
func NewTrainHypernetworkSdapiV1TrainHypernetworkPostOK() *TrainHypernetworkSdapiV1TrainHypernetworkPostOK {
	return &TrainHypernetworkSdapiV1TrainHypernetworkPostOK{}
}

/*
TrainHypernetworkSdapiV1TrainHypernetworkPostOK describes a response with status code 200, with default header values.

Successful Response
*/
type TrainHypernetworkSdapiV1TrainHypernetworkPostOK struct {
	Payload *models.TrainResponse
}

// IsSuccess returns true when this train hypernetwork sdapi v1 train hypernetwork post o k response has a 2xx status code
func (o *TrainHypernetworkSdapiV1TrainHypernetworkPostOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this train hypernetwork sdapi v1 train hypernetwork post o k response has a 3xx status code
func (o *TrainHypernetworkSdapiV1TrainHypernetworkPostOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this train hypernetwork sdapi v1 train hypernetwork post o k response has a 4xx status code
func (o *TrainHypernetworkSdapiV1TrainHypernetworkPostOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this train hypernetwork sdapi v1 train hypernetwork post o k response has a 5xx status code
func (o *TrainHypernetworkSdapiV1TrainHypernetworkPostOK) IsServerError() bool {
	return false
}

// IsCode returns true when this train hypernetwork sdapi v1 train hypernetwork post o k response a status code equal to that given
func (o *TrainHypernetworkSdapiV1TrainHypernetworkPostOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the train hypernetwork sdapi v1 train hypernetwork post o k response
func (o *TrainHypernetworkSdapiV1TrainHypernetworkPostOK) Code() int {
	return 200
}

func (o *TrainHypernetworkSdapiV1TrainHypernetworkPostOK) Error() string {
	return fmt.Sprintf("[POST /sdapi/v1/train/hypernetwork][%d] trainHypernetworkSdapiV1TrainHypernetworkPostOK  %+v", 200, o.Payload)
}

func (o *TrainHypernetworkSdapiV1TrainHypernetworkPostOK) String() string {
	return fmt.Sprintf("[POST /sdapi/v1/train/hypernetwork][%d] trainHypernetworkSdapiV1TrainHypernetworkPostOK  %+v", 200, o.Payload)
}

func (o *TrainHypernetworkSdapiV1TrainHypernetworkPostOK) GetPayload() *models.TrainResponse {
	return o.Payload
}

func (o *TrainHypernetworkSdapiV1TrainHypernetworkPostOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.TrainResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewTrainHypernetworkSdapiV1TrainHypernetworkPostUnprocessableEntity creates a TrainHypernetworkSdapiV1TrainHypernetworkPostUnprocessableEntity with default headers values
func NewTrainHypernetworkSdapiV1TrainHypernetworkPostUnprocessableEntity() *TrainHypernetworkSdapiV1TrainHypernetworkPostUnprocessableEntity {
	return &TrainHypernetworkSdapiV1TrainHypernetworkPostUnprocessableEntity{}
}

/*
TrainHypernetworkSdapiV1TrainHypernetworkPostUnprocessableEntity describes a response with status code 422, with default header values.

Validation Error
*/
type TrainHypernetworkSdapiV1TrainHypernetworkPostUnprocessableEntity struct {
	Payload *models.HTTPValidationError
}

// IsSuccess returns true when this train hypernetwork sdapi v1 train hypernetwork post unprocessable entity response has a 2xx status code
func (o *TrainHypernetworkSdapiV1TrainHypernetworkPostUnprocessableEntity) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this train hypernetwork sdapi v1 train hypernetwork post unprocessable entity response has a 3xx status code
func (o *TrainHypernetworkSdapiV1TrainHypernetworkPostUnprocessableEntity) IsRedirect() bool {
	return false
}

// IsClientError returns true when this train hypernetwork sdapi v1 train hypernetwork post unprocessable entity response has a 4xx status code
func (o *TrainHypernetworkSdapiV1TrainHypernetworkPostUnprocessableEntity) IsClientError() bool {
	return true
}

// IsServerError returns true when this train hypernetwork sdapi v1 train hypernetwork post unprocessable entity response has a 5xx status code
func (o *TrainHypernetworkSdapiV1TrainHypernetworkPostUnprocessableEntity) IsServerError() bool {
	return false
}

// IsCode returns true when this train hypernetwork sdapi v1 train hypernetwork post unprocessable entity response a status code equal to that given
func (o *TrainHypernetworkSdapiV1TrainHypernetworkPostUnprocessableEntity) IsCode(code int) bool {
	return code == 422
}

// Code gets the status code for the train hypernetwork sdapi v1 train hypernetwork post unprocessable entity response
func (o *TrainHypernetworkSdapiV1TrainHypernetworkPostUnprocessableEntity) Code() int {
	return 422
}

func (o *TrainHypernetworkSdapiV1TrainHypernetworkPostUnprocessableEntity) Error() string {
	return fmt.Sprintf("[POST /sdapi/v1/train/hypernetwork][%d] trainHypernetworkSdapiV1TrainHypernetworkPostUnprocessableEntity  %+v", 422, o.Payload)
}

func (o *TrainHypernetworkSdapiV1TrainHypernetworkPostUnprocessableEntity) String() string {
	return fmt.Sprintf("[POST /sdapi/v1/train/hypernetwork][%d] trainHypernetworkSdapiV1TrainHypernetworkPostUnprocessableEntity  %+v", 422, o.Payload)
}

func (o *TrainHypernetworkSdapiV1TrainHypernetworkPostUnprocessableEntity) GetPayload() *models.HTTPValidationError {
	return o.Payload
}

func (o *TrainHypernetworkSdapiV1TrainHypernetworkPostUnprocessableEntity) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.HTTPValidationError)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
