// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewTrainHypernetworkSdapiV1TrainHypernetworkPostParams creates a new TrainHypernetworkSdapiV1TrainHypernetworkPostParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewTrainHypernetworkSdapiV1TrainHypernetworkPostParams() *TrainHypernetworkSdapiV1TrainHypernetworkPostParams {
	return &TrainHypernetworkSdapiV1TrainHypernetworkPostParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewTrainHypernetworkSdapiV1TrainHypernetworkPostParamsWithTimeout creates a new TrainHypernetworkSdapiV1TrainHypernetworkPostParams object
// with the ability to set a timeout on a request.
func NewTrainHypernetworkSdapiV1TrainHypernetworkPostParamsWithTimeout(timeout time.Duration) *TrainHypernetworkSdapiV1TrainHypernetworkPostParams {
	return &TrainHypernetworkSdapiV1TrainHypernetworkPostParams{
		timeout: timeout,
	}
}

// NewTrainHypernetworkSdapiV1TrainHypernetworkPostParamsWithContext creates a new TrainHypernetworkSdapiV1TrainHypernetworkPostParams object
// with the ability to set a context for a request.
func NewTrainHypernetworkSdapiV1TrainHypernetworkPostParamsWithContext(ctx context.Context) *TrainHypernetworkSdapiV1TrainHypernetworkPostParams {
	return &TrainHypernetworkSdapiV1TrainHypernetworkPostParams{
		Context: ctx,
	}
}

// NewTrainHypernetworkSdapiV1TrainHypernetworkPostParamsWithHTTPClient creates a new TrainHypernetworkSdapiV1TrainHypernetworkPostParams object
// with the ability to set a custom HTTPClient for a request.
func NewTrainHypernetworkSdapiV1TrainHypernetworkPostParamsWithHTTPClient(client *http.Client) *TrainHypernetworkSdapiV1TrainHypernetworkPostParams {
	return &TrainHypernetworkSdapiV1TrainHypernetworkPostParams{
		HTTPClient: client,
	}
}

/*
TrainHypernetworkSdapiV1TrainHypernetworkPostParams contains all the parameters to send to the API endpoint

	for the train hypernetwork sdapi v1 train hypernetwork post operation.

	Typically these are written to a http.Request.
*/
type TrainHypernetworkSdapiV1TrainHypernetworkPostParams struct {

	// Body.
	Body interface{}

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the train hypernetwork sdapi v1 train hypernetwork post params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *TrainHypernetworkSdapiV1TrainHypernetworkPostParams) WithDefaults() *TrainHypernetworkSdapiV1TrainHypernetworkPostParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the train hypernetwork sdapi v1 train hypernetwork post params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *TrainHypernetworkSdapiV1TrainHypernetworkPostParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the train hypernetwork sdapi v1 train hypernetwork post params
func (o *TrainHypernetworkSdapiV1TrainHypernetworkPostParams) WithTimeout(timeout time.Duration) *TrainHypernetworkSdapiV1TrainHypernetworkPostParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the train hypernetwork sdapi v1 train hypernetwork post params
func (o *TrainHypernetworkSdapiV1TrainHypernetworkPostParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the train hypernetwork sdapi v1 train hypernetwork post params
func (o *TrainHypernetworkSdapiV1TrainHypernetworkPostParams) WithContext(ctx context.Context) *TrainHypernetworkSdapiV1TrainHypernetworkPostParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the train hypernetwork sdapi v1 train hypernetwork post params
func (o *TrainHypernetworkSdapiV1TrainHypernetworkPostParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the train hypernetwork sdapi v1 train hypernetwork post params
func (o *TrainHypernetworkSdapiV1TrainHypernetworkPostParams) WithHTTPClient(client *http.Client) *TrainHypernetworkSdapiV1TrainHypernetworkPostParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the train hypernetwork sdapi v1 train hypernetwork post params
func (o *TrainHypernetworkSdapiV1TrainHypernetworkPostParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the train hypernetwork sdapi v1 train hypernetwork post params
func (o *TrainHypernetworkSdapiV1TrainHypernetworkPostParams) WithBody(body interface{}) *TrainHypernetworkSdapiV1TrainHypernetworkPostParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the train hypernetwork sdapi v1 train hypernetwork post params
func (o *TrainHypernetworkSdapiV1TrainHypernetworkPostParams) SetBody(body interface{}) {
	o.Body = body
}

// WriteToRequest writes these params to a swagger request
func (o *TrainHypernetworkSdapiV1TrainHypernetworkPostParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error
	if o.Body != nil {
		if err := r.SetBodyParam(o.Body); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
