// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewUnloadapiSdapiV1UnloadCheckpointPostParams creates a new UnloadapiSdapiV1UnloadCheckpointPostParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewUnloadapiSdapiV1UnloadCheckpointPostParams() *UnloadapiSdapiV1UnloadCheckpointPostParams {
	return &UnloadapiSdapiV1UnloadCheckpointPostParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewUnloadapiSdapiV1UnloadCheckpointPostParamsWithTimeout creates a new UnloadapiSdapiV1UnloadCheckpointPostParams object
// with the ability to set a timeout on a request.
func NewUnloadapiSdapiV1UnloadCheckpointPostParamsWithTimeout(timeout time.Duration) *UnloadapiSdapiV1UnloadCheckpointPostParams {
	return &UnloadapiSdapiV1UnloadCheckpointPostParams{
		timeout: timeout,
	}
}

// NewUnloadapiSdapiV1UnloadCheckpointPostParamsWithContext creates a new UnloadapiSdapiV1UnloadCheckpointPostParams object
// with the ability to set a context for a request.
func NewUnloadapiSdapiV1UnloadCheckpointPostParamsWithContext(ctx context.Context) *UnloadapiSdapiV1UnloadCheckpointPostParams {
	return &UnloadapiSdapiV1UnloadCheckpointPostParams{
		Context: ctx,
	}
}

// NewUnloadapiSdapiV1UnloadCheckpointPostParamsWithHTTPClient creates a new UnloadapiSdapiV1UnloadCheckpointPostParams object
// with the ability to set a custom HTTPClient for a request.
func NewUnloadapiSdapiV1UnloadCheckpointPostParamsWithHTTPClient(client *http.Client) *UnloadapiSdapiV1UnloadCheckpointPostParams {
	return &UnloadapiSdapiV1UnloadCheckpointPostParams{
		HTTPClient: client,
	}
}

/*
UnloadapiSdapiV1UnloadCheckpointPostParams contains all the parameters to send to the API endpoint

	for the unloadapi sdapi v1 unload checkpoint post operation.

	Typically these are written to a http.Request.
*/
type UnloadapiSdapiV1UnloadCheckpointPostParams struct {
	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the unloadapi sdapi v1 unload checkpoint post params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *UnloadapiSdapiV1UnloadCheckpointPostParams) WithDefaults() *UnloadapiSdapiV1UnloadCheckpointPostParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the unloadapi sdapi v1 unload checkpoint post params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *UnloadapiSdapiV1UnloadCheckpointPostParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the unloadapi sdapi v1 unload checkpoint post params
func (o *UnloadapiSdapiV1UnloadCheckpointPostParams) WithTimeout(timeout time.Duration) *UnloadapiSdapiV1UnloadCheckpointPostParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the unloadapi sdapi v1 unload checkpoint post params
func (o *UnloadapiSdapiV1UnloadCheckpointPostParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the unloadapi sdapi v1 unload checkpoint post params
func (o *UnloadapiSdapiV1UnloadCheckpointPostParams) WithContext(ctx context.Context) *UnloadapiSdapiV1UnloadCheckpointPostParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the unloadapi sdapi v1 unload checkpoint post params
func (o *UnloadapiSdapiV1UnloadCheckpointPostParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the unloadapi sdapi v1 unload checkpoint post params
func (o *UnloadapiSdapiV1UnloadCheckpointPostParams) WithHTTPClient(client *http.Client) *UnloadapiSdapiV1UnloadCheckpointPostParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the unloadapi sdapi v1 unload checkpoint post params
func (o *UnloadapiSdapiV1UnloadCheckpointPostParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WriteToRequest writes these params to a swagger request
func (o *UnloadapiSdapiV1UnloadCheckpointPostParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
