name: Check Intersvc Support List

# 支持手动触发
on:
  workflow_dispatch:
    inputs:
      action:
        description: 'Action to execute'
        required: true
        default: 'Check Intersvc Support List'

jobs:
  check_intersvc_support_list:
    runs-on: ubuntu-latest  # 选择适合你的操作系统环境

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.10.12 

    - name: Run script
      id: run_script
      run: |
        python3 .action_script/gen_intersvc_support_list.py >> list.md
    
    - name: Configure Git
      run: |
        git config --global user.name "GitHub Actions Bot"

    - name: Clone Wiki repository
      run: git clone https://${{ env.GITHUB_TOKEN }}@github.com/${{ github.repository }}.wiki.git
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Update Wiki
      run: |
        ls
        repository_full_name=${{ github.repository }}
        repository_name=${repository_full_name##*/}
        cd ./$repository_name.wiki
        cp -f ../list.md ./Intersvc-Support-List.md
        git commit -am "Update Support List"
        git push
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}