name: Check Intersvc Support List

# 支持手动触发
on:
  workflow_dispatch:
    inputs:
      action:
        description: 'Action to execute'
        required: true
        default: 'Check Intersvc Support List'

jobs:
  check_intersvc_support_list:
    runs-on: ubuntu-latest  # 选择适合你的操作系统环境

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.10.12 

    - name: Run script
      id: run_script
      run: |
        python3 .action_script/gen_intersvc_support_list.py >> list.md
        echo "SP_LIST=$(cat list.md)" >> $GITHUB_OUTPUT

    - name: Checkout Wiki
      uses: actions/checkout@v2
      with:
        repository: ${{ github.repository }}.wiki

    - name: Update Wiki
      run: |
        git config --global user.name "GitHub Actions Bot"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        # 把SP_LIST的内容写入到Intersvc-Support-List.md中
        echo "${{ SP_LIST }}" > ./Intersvc-Support-List.md
        git commit -am "Update Support List"
      env:
        SP_LIST: ${{ steps.run_script.outputs.SP_LIST }}

    - name: Push Wiki
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        repository: ${{ github.repository }}.wiki