name: Check Intersvc Support List

# 支持手动触发
on:
  workflow_dispatch:
    inputs:
      action:
        description: 'Action to execute'
        required: true
        default: 'Check Intersvc Support List'

jobs:
  run_script:
    runs-on: ubuntu-latest  # 选择适合你的操作系统环境

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.10.12 

    - name: Run script
      id: run_script
      run: |
        python .action_script/gen_intersvc_support_list.py
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}